% Versione branch 8uno
\documentclass[fontsize=11pt,
captions=tableheading,
captions=figureheading,
a4paper,
headsepline=true,
footsepline=true,
open=right,
titlepage,
final]{scrbook}

% draft/final onecolumn/twocolumn oneside/twoside openany/openright
% Circa 80 lettere per pagina con draft al posto di final fa il pdf senza foto
\usepackage{scrlayer-scrpage}
%\usepackage[toc, page]{appendix}

\usepackage[english, italian]{babel}
% per la sillabazione corretta e per biblatex
% \usepackage[english]english serve se c'e' bisogno di una parte da scrivere in inglese

% https://tex.stackexchange.com/questions/82993/how-to-change-the-name-of-document-elements-like-figure-contents-bibliogr

\usepackage[sc]{mathpazo}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
% \usepackage{geometry}
% \geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=5cm}
% \usepackage[nochapters,pdfspacing,dottedtoc]{classicthesis}
% \setcounter{secnumdepth}{4} % numerini alle sezioni dentro al testo
% \setcounter{tocdepth}{4} % nell'indice
\usepackage{url}
\usepackage{comment}

% hyperref serve per i link
% Tutti le opzioni che ci sono adesso non sappiamo se servono: le disattivo per il momento
% 
\usepackage[]{hyperref} % caricare questo prima di floats per evitare casini
% unicode=true, pdfusetitle, backref=false, pdfborder={0 0 1},
% bookmarks=true, bookmarksnumbered=true, bookmarksopen=true, bookmarksopenlevel=2, colorlinks=false,
% breaklinks=false

%% xcolor serve per colorare il testo
\usepackage[dvipsnames]{xcolor}
%% Questa parte sotto controlla i colori dei riferimenti cliccabili
\hypersetup{colorlinks,
  linkcolor={red!50!black},
  citecolor={red},
  urlcolor={blue!80!black},
  pdfstartview={XYZ null null 1}
}
% \usepackage{textcomp}
% Sperimentale per le liste; non attivare
%% \usepackage{enumitem}
%% \setlist{nosep} %

%%\usepackage{longtable} % per avere tabelle spezzate tra le pagine
%%\usepackage{tabularx} % per le tabelle con molto testo
\usepackage{lscape} % per ruotare qualche pagina in landscape
\usepackage{booktabs} % per fare tabelle semplici come nei libri (top mid e bottomrule)

\usepackage{setspace} % permette di cambiare la spaziatura quando necessario
%\doublespacing % per avere spazio per scrivere a penna
\onehalfspacing  % per l'interlinea finale
% meglio questi due comandi sopra che linespread.
% Cosi sistema interlinea 1 nelle tabelle automaticamente
% \linespread{1.3} % Di default è \linespread{1} che corrisponde
% all'interlinea uno; 1.3 sta per interlinea 1 e mezzo

%% \usepackage{multirow} % tabelle multiriga e multicolonna

%% \usepackage{threeparttable}
% vedi http://www.tug.org/pracjourn/2007-2/asknelly/

%% \usepackage{lineno}
%% \linenumbers
% Queste due righe sopra aggiungono la numerazione delle righe
% scommentare nella versione finale

% Queste righe sotto si occupano della bibliografia
% \usepackage[babel]{csquotes}


\usepackage[backend=biber, sorting=nyt, style=authoryear,
            autolang=hyphen, natbib=true, backref]{biblatex}
%% style=numeric

% nty Sort by name, title, year.
% nyt Sort by name, year, title.
% nyvt Sort by name, year, volume, title.
% anyt Sort by alphabetic label, name, year, title.
% anyvt Sort by alphabetic label, name, year, volume, title.
% ynt Sort by year, name, title.
% ydnt Sort by year (descending), name, title.
% none Do not sort at all. All entries are processed in citation order.
% Debug Sort by entry key. This is intended for debugging only.

%% Qui sotto ci va il nome del file della bibliografia
\bibliography{bibliomone.bib}
% non ho capito a che serve ma dovrebbe essere utile a citare R in bib
% \newcommand{\code}[1]{\texttt{\smaller #1}}

\DeclareBibliographyCategory{cartaceo}
\DeclareBibliographyCategory{web}

\defbibheading{cartaceo}{\subsection*{Bibliografia}}
\defbibheading{web}{\subsection*{Siti Web consultati}}

%% siunitx serve per le unità di misura
\usepackage{siunitx}
\sisetup{detect-all = true, detect-family = true, output-decimal-marker = {,}}
% http://tex.stackexchange.com/questions/66713/can-i-make-siunitx-commands-use-serif-fonts-like-the-rest-of-the-math-in-beamer

%% questa roba sotto serve per non perdere il filo sulle copie stampate
%% commentare opportunamente nella versione finale
\usepackage[short, hhmmss]{datetime}
%\usepackage{fancyhdr}
\usepackage{placeins}
\usepackage{graphicx} %per le figure
%\pagestyle{fancy}
% \setlength{\headheight}{14pt} % il compilatore si lamenta che c'e' poco spazio 1 ott 2016 Siena
\usepackage[]{subfig} % per le figure affiancate

\usepackage{float}
% per forzare il posizionamento delle figure

%% \usepackage[normalem]{ulem}
% serve per barrare del testo in fase di correzione
% se non si usa [normalem], \emph sottolinea invece di fare il suo dovere

%% Pezzo per scrivere note a margine
\usepackage{xargs} % Use more than one optional parameter in a new commands
\usepackage[colorinlistoftodos, prependcaption, italian, textsize=scriptsize]{todonotes}
\newcommandx{\dubbio}[2][1=]{\todo[linecolor=red,backgroundcolor=red!25,bordercolor=red,#1]{#2}}
\newcommandx{\cambia}[2][1=]{\todo[linecolor=blue,backgroundcolor=blue!25,bordercolor=blue,#1]{#2}}
\newcommandx{\info}[2][1=]{\todo[linecolor=OliveGreen,backgroundcolor=OliveGreen!25,bordercolor=OliveGreen,#1]{#2}}
\newcommandx{\migliora}[2][1=]{\todo[linecolor=Plum,backgroundcolor=Plum!25,bordercolor=Plum,#1]{#2}}
\newcommandx{\fatto}[2][1=]{\todo[linecolor=gray, backgroundcolor=black!75]{#2}}
\newcommandx{\nonvisibile}[2][1=]{\todo[disable,#1]{#2}}
% \presetkeys{todonotes}{fancyline}{}
% Vediamo se con questo si riduce lo spazio tra la caption.
\usepackage[font=small, textfont=it, labelfont=bf, format=plain]{caption}

%\usepackage[raggedright]{titlesec}
% Serve per evitare la sillabazione nei titoli

%\newcommand{\sectionbreak}{\clearpage}
%% serve per mettere ogni section a pagina nuova

%\renewcommand{\chaptermark}[1]{\markboth{\thechapter.\space#1}{}}
%\renewcommand{\headrulewidth}{0.4pt}
%\renewcommand{\footrulewidth}{0.2pt}
% \cfoot{Pag. \thepage\, Compilata il \today\ alle \currenttime}
% \lfoot{}
% \rfoot{}
% E Even page
% O Odd page
% L Left field
% C Center field
% R Right field
% H Header
% F Footer
% \fancyhead{} % clear all header fields
\usepackage{enumitem}
% per fare l'itemize con il tondo intorno ai numeri
% e altri controlli sulle liste

%\usepackage[font=it, labelfont=bf, format=plain, skip=40pt]{caption}
% The optional argument of \setcapwidth is not supported and will be ignored if used in con-
% junction with the caption package. Furthermore the KOMA-Script options tablecaption-
% 30above & tablecaptionbelow and the commands \captionabove & \captionbelow
% are stronger than the position= setting offered by the caption package.
% \DeclareCaptionFont{mysize}{\fontsize{10}{9.6}\selectfont}
% \captionsetup{font=mysize}
% \usepackage[swapnames]{frontespizio} %per il frontespizio
\usepackage{frontespizio}

\newenvironment{abstract}%
{\cleardoublepage\null \vfill\begin{center}%
    \bfseries \abstractname \end{center} \footnotesize}%\doublespace }%
{\vfill\null}

\newenvironment{engabstract}%
{\cleardoublepage\null \vfill\begin{center}%
    \bfseries Summary  \end{center} \footnotesize}%\doublespace }%
{\vfill\null}

%% https://tex.stackexchange.com/questions/202512/translate-appendices-from-addappheadtotoc-in-other-languages-with-polyglossia
% \addto\captionsitalian{%
%   \renewcommand{\appendixtocname}{Appendici}%
%   \renewcommand{\appendixpagename}{Appendici}%
% }

\renewcommand{\theequation}{Eq. \arabic{equation}}
\usepackage{environ}
\NewEnviron{modello}{%
  \begin{equation}
    \BODY
  \end{equation}
}

\usepackage{amsmath}
\numberwithin{equation}{chapter} % numera le equazioni col numero di capitolo

\usepackage[nogin]{Sweave}
% https://tex.stackexchange.com/questions/11619/resize-arrays-and-figures-in-a-sweave-document
% nogin serve per definiore le dimensioni delle figure e passarle a latex

\DeclareSIUnit\atm{atm}
\DeclareSIUnit\torr{torr}

\usepackage{lipsum}
% blocchi di testo fittizi

<<PacchettiRichiesti, echo=FALSE, eval=TRUE>>=
library(nlme)
library(plyr)
library(lattice)
library(xtable)
library(foreign)
library(agricolae)
library(multcomp)
@

<<setupDir, include=FALSE, cache=FALSE, echo=FALSE>>=
info.sistema <-
Sys.info()[c(1,7)]
if(info.sistema[1]=="Windows"){
  DirMain <- paste("C:/Users/", info.sistema[2], "/Dropbox/MOLTE_R", sep="")
} else {
  if(info.sistema[2]=="simone" ){
    DirMain <-"~/Simo_GIT"
  }else{
    DirMain <-"~/Documenti/BitBucket/Simo_GIT"
  }
}
DirData <-
file.path(DirMain,"dati_grezzi")
DirElab <-
file.path(DirMain,"dati_elaborati")
DirGraf <-
file.path(DirMain, "grafici")
DirFunz <-
file.path(DirMain, "funzioni")
DirCod <-
file.path(DirMain, "codice")
DirTab <-
file.path(DirMain, "tabelle")
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
\author{Simone Massenzio}
\title{25 anni di conduzione Biologica: uno studio di fisica del suolo}
\begin{document}
% \begin{frontespizio}
%   \Universita{Università degli studi di Firenze}
%   \Facolta{Agraria}
%   
%   \Corso{Scienze e tecnologie agrarie}
%   \Annoaccademico{2016-2017}
%   \Titolo{Tesi di laurea magistrale}
%   %   \Sottotitolo{Svolto da Simone Massenzio,\\ residente in Via don Minzoni 31A 59011 - Carmignano (PO), \\
%       %   tel.: 3336277649, e-mail: simone.massenzio@stud.unifi.it\\ Svolto nel periodo compreso tra il 05/12/2016 e il 08/03/2017}
%   \NCandidato{Candidato}
%   \Candidato{Simone Massenzio}
%   \NRelatore{Relatore}{relatore}
%   \Relatore{Dott. Ottorino-Luca Pantani}
%   \NCorrelatore{Correlatore}{Correlatore}
%   \Correlatore{Dott. Luigi P. D'Acqui}
% \end{frontespizio}
\begin{frontespizio}
  \Margini{5cm}{1.5cm}{3cm}{1cm}
  \Logo[2.5cm]{logo-unifi_positivo.jpeg}
  \Istituzione{Universit\`a degli Studi di Firenze}
  \Divisione{Scuola di Agraria}
  \Scuola{Corso di Laurea in Scienze e tecnologie agrarie (LM-69)}
  \Titolo{25 anni di conduzione Biologica}
  \Sottotitolo{Uno studio di fisica del suolo}
  \NCandidato{Candidato}
  \Candidato{Simone Massenzio}
  \NRelatore{Relatore}{}
  \Relatore{Dott. Ottorino-Luca Pantani}
  \NCorrelatore{Correlatori}{Correlatori}
  \Correlatore{Dott. Luigi Paolo D'Acqui}
  \Correlatore{Prof. Gaio Cesare Pacini}
  \Piede{Anno accademico 2016-2017}
\end{frontespizio}
% \maketitle


\listoftodos %messo qui per non rischiare di scordarselo alla stampa finale


\begin{abstract}
  Lo scopo di questa tesi \`e quello di: \textbf{i)} comparare due
  sistemi di conduzione agricola (Biologico e Convenzionale, attivi da
  venticinque anni) studiando tre propriet\`a fisiche del suolo:
  densit\`a apparente, distribuzione dei pori e stabilità degli
  aggregati; \textbf{ii)} comparare gli effetti di tre lavorazioni
  primarie: aratura, rippatura e frangizollatura. Lo studio \`e
  inserito nel progetto MOLTE, un \textbf{long term experiment}
  dell'Universit\`a di Firenze dove, dal 1991 presso l'azienda
  agricola Montepaldi, situata a San Casciano val di Pesa (FI), viene
  condotta una sperimentazione sul sistema Biologico. I risultati
  delle analisi sulla densit\`a apparente mostrano differenze
  statisticamente significative tra i trattamenti, tuttavia i
  cambiamenti sono minimi rendendoli non rilevanti dal punto
  di vista pratico. Invece i risultati delle analisi sulla
  distribuzione dei pori non mostrano differenze statisticamente
  significative, mentre quelle sulla stabilit\`a degli aggregati
  indicano una maggior stabilit\`a degli aggregati nei suoli a
  conduzione Convenzionale rispetto a quella Biologica.
\end{abstract}


\begin{otherlanguage*}{english}
  \begin{engabstract}
    The purposes of this work were: \textbf{i)} to compare two farming
    systems (organic and conventional management on site since twenty
    five years) through the assessement of three soil's physical
    properties such as: bulk density, pore size distribution and
    aggregate stability; \textbf{ii)} to compare the effects of three
    tillage systems: plowing, chisel plowing and disk harrowing. The
    study is implemented within the \emph{MOLTE} project, a long term
    experiment of the University of Florence where, since 1991, at
    Montepaldi farm, located in San Casciano val di Pesa (FI) was
    carried out an experimentation on organic farming systems.
    The result of the analysis of the bulk density, show
    statistically significant differences between two farming systems,
    however these difference were so small that are negligible from a
    practical point of view. On the contrary the results of the pore size distribution 
    do not display statistically significant differences. 
    The aggregate stability shows that the aggregates from the conventional 
    soil are more stable than those from the organic one. 
  \end{engabstract}%
\end{otherlanguage*}

\tableofcontents
\newpage
% \fancyhead[RO,LE]{}
% \fancyfoot{} % clear all footer fields
% \fancyfoot[RE,LO]{Tesi Simone Massenzio}
% \fancyfoot[C]{\today\  \currenttime}
% \fancyfoot[LE,RO]{\thepage}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 

\chapter{Il suolo in sistemi agricoli Convenzionali e Biologici}



Il concetto di suolo o terreno \`e piuttosto chiaro nell'immaginario
collettivo; nonostante questo \`e difficile individuare una
definizione univoca. Un tentativo di definizione \`e quello di
\citet{JOHNSON19986}: \emph{suolo è qualsiasi materiale minerale e
  organico posto alla superficie di pianeti o corpi simili, alterato
  da agenti biologici, chimici e/o fisici.}

Nella definizione di Johnson non vengono considerate le piante; la
"Soil Taxonomy" americana (USDA) ha fornito una definizione pi\`u completa in cui vengono
considerati anche gli organismi vegetali: \emph{Il suolo \`e un
  corpo naturale composto da una fase solida (minerale e organica),
  una fase liquida e una gassosa presenti sulla superficie terrestre,
  occupa spazio ed \`e caratterizzato da una o pi\`u delle seguenti
  caratteristiche: orizzonti, o strati, che sono distinguibili dal
  materiale iniziale grazie alle aggiunte, perdite, trasferimenti e
  trasformazioni di energia e materia o l'abilit\`a di supportare
  piante vascolari in un ambiente naturale} \citep{united1999soil}.


Dal suolo naturale distinguiamo il terreno agrario; questo è
caratterizzato da pesanti modifiche operate dall'uomo mediante
lavorazioni meccaniche, concimazioni e sistemazioni idrauliche.  Lo
scopo di queste operazioni è quello di aumentare il più possibile la
produzione alimentare umana e animale, mantenendo costante la
fertilit\`a del terreno.

Secondo \citet{ellis1996soil}: \emph{la
  fertilit\`a di un suolo si riferisce alla sua abilit\`a di
  fornire in maniera adeguata e proporzionata nutrienti e acqua
  necessari per la crescita e la riproduzione delle piante, e
  all'assenza di sostanze tossiche che possono inibirle.}

Tuttavia, lo sfruttamento intensivo del suolo degli ultimi 50 anni, ne ha
provocato la degradazione determinando una diminuzione della sua
fertilit\`a.

A fronte di un previsto aumento di popolazione mondiale, \`e pi\`u che mai
necessario individuare delle tecniche che permettano il mantenimento delle
caratteristiche dei terreni agrari senza diminuirne la
produttivit\`a. Gli stessi consumatori occidentali sono pi\`u attenti
ai loro acquisti e cercano prodotti che siano coltivati rispettando
l'ambiente e con un basso impatto ambientale. In particolare sono
sempre pi\`u richiesti prodotti di agricoltura Biologica che hanno
l'obiettivo di impattare il meno possibile l'ambiente utilizzando
prodotti naturali e non di sintesi.

Nonostante questo, non \`e stato dimostrato scientificamente in
maniera inequivocabile la superiorit\`a dell'agricoltura Biologica
rispetto all'agricoltura Convenzionale. Ci\`o pu\`o essere dovuto ad
alcuni dei problemi che la ricerca scientifica deve fronteggiare nello
studio dell'agricoltura Biologica:
\begin{itemize}
\item ogni ambiente agrario ha le sue caratteristiche pedoclimatiche e
  risponde in maniera diversa alle varie tecniche agricole, inoltre
  anche le colture agrarie hanno esigenze molto diverse;
\item non esiste un indicatore di fertilit\`a univoco che permette di confrontare i
  vari tipi di agricoltura.
\end{itemize}


\section{Caratteristiche generali del suolo}
Il suolo è un sistema naturale trifasico costituito da:
\begin{itemize}%%[topsep=0ex, itemsep=1ex, parsep=1ex, partopsep=1ex]
\item  fase solida, materiale minerale e materiale
  organico vivo o in decomposizione;
\item fase liquida, ovvero una soluzione acquosa di cationi,
  anioni e composti organici;
\item fase gassosa, simile per composizione a quella atmosferica.
\end{itemize}

In linea di massima, il 50\% del suolo è composto dalla fase solida
(di cui il 5\% è materiale organico), il 30\% dalla fase liquida e il
20\% dalla fase gassosa, anche se queste ultime due variano
reciprocamente a seconda delle condizioni atmosferiche.

La formazione del suolo è un processo estremamente complesso in cui
intervengono fattori fisici (frantumazione, alternanza gelo/disgelo,
alternanza di idratazione ed essiccamento), chimici (reazioni
acido-base, ossidoriduzioni) e biologici (fermentazioni o, in
generale, processi operati da microrganismi, piante e animali).
Secondo \citet{jenny1994factors} i fattori che intervengono nella
formazione del suolo possono essere descritti con la seguente funzione:
\begin{equation}
  s = f(cl, o, r, p, t, ...)
\end{equation}

Dove:\\
\begin{tabular}{rl}
  $s$  &  sono le propriet\`a del suolo\\
  $cl$ &  \`e il clima\\
  $o$  &  sono i fattori biologici\\
  $r$  &  \`e la topografia\\
  $p$  &  \`e la roccia madre\\
  $t$  &  \`e il tempo\\
       &  ulteriori fattori secondari
\end{tabular}
\vspace*{3em}

Nel terreno, data la sua influenza verso gli altri parametri fisici e
chimici del suolo, è importante la distribuzione granulometrica, o tessitura,
in cui le particelle di diametro superiore a \SI{2}{\milli\metre} sono
definite scheletro, quelle comprese tra \SI{2}{\mm} e \SI{50}{\micro\metre} sono
definite sabbia, quelle comprese tra \SI{50}{\micro\metre} e \SI{2}{\micro\metre}
sono definite limo e quelle inferiori a \SI{2}{\micro\metre} sono definite
argilla. La tessitura \`e usualmente rappresentata mediante il
triangolo tessiturale introdotto da Whitney nel 1911 e adottata
dall'USDA come metodo di rappresentazione ufficiale; la versione
attuale (Fig. \ref{fig:triangolo}), modificata dal triangolo
tessiturale di Whitney, \`e stata introdotta nel 1951 \citep{SoilTr}.

\begin{figure}[ht]
  \centering
  \includegraphics[width=0.7\textwidth]{../foto/USDA_triangolo.jpeg}
  \caption[Il triangolo tessiturale]{Triangolo tessiturale secondo USDA}
  \label{fig:triangolo}
\end{figure}
\FloatBarrier

La presenza di cementi, organici o minerali, che portano alla
formazione di aggregati permette di definire la
struttura del terreno come \emph{il particolare modo di aggregarsi dei
  suoi vari componenti in rapporto soprattutto all'azione "legante"
  della frazione colloidale, organica e inorganica.}
\citep{tassinari1976manuale}.

Essendo il risultato dei fattori di formazione del suolo sopra
elencati, la tessitura non risente particolarmente delle diverse
tecniche agronomiche, mentre la struttura viene notevolmente
condizionata dalla tecnica agronomica con effetti sulle propriet\`a
fisiche, meccaniche e chimiche del suolo, e quindi sulla maggiore o
minore fertilit\`a.

La particelle solide che costituiscono il suolo, hanno un diverso
valore di densit\`a, in funzione del materiale di cui sono
costituite. Questo non \`e uniforme per tutti i componenti (varia da
circa 2 a oltre 3) ma, in considerazione del fatto che nel suolo sono
presenti prevalentemente i silicati (con densit\`a che varia da 2,5 a
2,8), si assume il valore di \SI{2.65}{\gram\per\cubic\centi\metre}
\citep{radaelli2001chimica}. Questo valore \`e, a fini pratici,
costante, considera la sola frazione minerale ed \`e preso
come valore di riferimento della densit\`a reale.

Per considerare, oltre alla fase solida, anche i vuoti si utilizza un
altro valore di densit\`a: la densit\`a apparente. Come detto
precedentemente, questo valore considera anche i vuoti ed \`e legato
principalmente alla distribuzione granulometrica e alla
struttura. Secondo \citet{AskinBulkDensity}, la densit\`a apparente
di un terreno è influenzata principalmente dalla tessitura del
terreno, e pi\`u in particolare, dalla frazione sabbiosa e
argillosa. Tuttavia, anche se con un effetto pi\`u lieve, questi
autori riscontrano una significativa correlazione negativa tra il
contenuto di sostanza organica e il valore della densit\`a apparente.

%% Simo Tutta sta roba l'ho presa da Pagliai

La porosit\`a del terreno è un ulteriore parametro fondamentale per le
caratteristiche fisiche del suolo: il volume dei pori rispetto al
volume della fase solida influenza notevolmente il contenuto idrico e
la lavorabilit\`a del terreno. La sua misura può aiutare la
quantificazione dell’impatto delle pratiche colturali sul suolo ed è
il miglior indicatore per la qualit\`a della struttura
\citep{pagliai2002soil}. La valutazione dei pori in termini di forma,
spazio, dimensione, continuit\`a, orientamento e arrangiamento
permette di definire la complessit\`a della struttura e fa capire le
modificazioni indotte dalle pratiche colturali; in questo modo è
possibile indicare quali di queste siano più compatibili con la
protezione ambientale. 

La porosit\`a ha relazioni con la resistenza alla penetrazione: la
diminuzione del volume dei pori è solitamente associata ad un aumento
della resistenza alla penetrazione. Sia la forma dei pori che la
distribuzione della loro grandezza, influenza direttamente le
propriet\`a chimiche, biochimiche e biologiche.  In particolare, una
buona struttura del suolo promuove l'approfondimento radicale e i
movimenti di acqua, aria e fauna tellurica.  Invece una cattiva
struttura favorisce l'erosione, la compattazione e la
desertificazione.

Secondo \citet{pagliai2002soil}, la classificazione dei suoli più
usata è quella di \citet{greenland1977soil} ed \`e mostrata in tabella
\ref{tab:green}. \migliora{Luigi dice di mettere più classificazioni con la pubblicazione che mi ha dato.}
 \todo[inline]{Son d'accordo e forse meglio una figura}

\begin{table}[ht]
  \caption[Classificazione dei pori del terreno secondo le
  dimensioni]{Classificazione dei pori del terreno secondo le
    dimensioni: da \citet{pagliai2002soil}.}
  \label{tab:green}
  \centering
  \begin{tabular}{lll}
    \toprule
    Diametro pori & Potenziale idrico & Nome\\
    \SI{}{\micro\metre}  & \SI{}{\bar} & \\
    \midrule
    < 0,005    & > -600        & Spazi di legame\\
    0,005-0,5 & -600/-6        & Pori residui\\
    0,5-50    & - 6/- 0,06     & Pori di immagazzinamento\\
    50-500    & - 0,06/- 0,006 & Pori di trasmissione\\
    > 500      & <- 0,006      & Fessure\\
    \bottomrule
  \end{tabular}
\end{table}

I pori con diametro inferiore ai \SI{0.005}{\micro\meter} sono
chiamati \emph{pori di legame} e sono particolarmente importanti per
quanto riguarda le forze che tengono insieme la particelle primarie in
\emph{domains}.


I pori di diametro inferiore a \SI{0.5}{\micro\metre} sono definiti
\emph{pori residui} per le loro interazioni chimiche a livello
molecolare; i pori che hanno un diametro compreso tra 0,5 e
\SI{50}{\micro\metre} sono detti \emph{pori di immagazzinamento},
quelli con diametro compreso tra 50 e \SI{500}{\micro\metre} sono i \emph{pori di
  conduzione}. I pori di dimensioni maggiori di \SI{500}{\micro\metre}
sono utili alla penetrazione delle radici e al movimento dell’acqua di
drenaggio specialmente nei suoli a tessitura fine. Cionondimeno, una loro
percentuale pari o superiore al 70-80\% della porosit\`a totale,
indica una cattiva struttura che non favorisce la crescita delle
piante. Se i pori grandi, medi e piccoli sono in proporzione ottimale,
si osserva un concomitante immagazzinamento/conduzione di acqua e aria
che permette un'adeguata crescita radicale.

Un ulteriore indicatore di fertilit\`a fisica del suolo \`e la
stabilit\`a degli aggregati; questi ultimi sono definiti come \emph{un
  insieme di particelle primarie di suolo legate l'un l'altra in modo
  maggiore rispetto alle particelle adiacenti}, mentre la stabilit\`a
degli aggregati \`e \emph{la capacit\`a degli aggregati di suolo di
  resistere alla rottura quando vengono applicate forze esterne
  (solitamente dall'acqua)} \citep{SoilQualStab}. L'importanza della
stabilit\`a degli aggregati si esplica soprattutto durante una
pioggia, in quanto l'erosione \`e collegata direttamente alla
resistenza degli aggregati \citep{de1985aggregate,
  bissonnais1996aggregate}. In molti tipi di suoli \`e stato visto
come la stabilit\`a degli aggregati dipenda dalla quantit\`a di
sostanza organica e quindi, in un suolo
agrario, dalla gestione dell'agroecosistema \citep{tisdall1982organic}.

Sono diversi i meccanismi che provocano la rottura degli aggregati \citep{EJSS4_12311}:
\begin{itemize}
  \item rottura per compressione di aria intrappolata (\emph{slaking});
  \item rottura per rigonfiamento asimmetrico;
  \item rottura per impatto della pioggia;
  \item dispersione fisico-chimica;
\end{itemize}
Lo \emph{slaking} consiste nella rottura degli aggregati di suolo
causata dall'aria intrappolata dentro all'aggregato durante
l'inumidimento; avviene quando gli aggregati secchi sono immersi in
acqua e si bagnano rapidamente, l'effetto dipende dal volume dell'aria
intrappolata e dalla velocit\`a di inumidimento, i frammenti
risultanti dallo \emph{slaking} sono principalmente microaggregati e
aumentano in dimensioni all'aumentare del contenuto di argilla; lo
\emph{slaking} diminuisce all'aumentare dell'umidit\`a
\citep{le1988comportement, truman1990antecedent} .

La rottura per rigonfiamento asimmetrico, \`e un meccanismo molto
simile al precedente: ha lo stesso effetto ed \`e generato dalle
stesse condizioni dello \emph{slaking}, la differenza sta nel
meccanismo fisico con cui avviene. Inoltre, al contrario dello
\emph{slaking}, questo processo aumenta all'aumentare del contenuto in
argilla \citep{chan1994slaking}.

La rottura degli aggregati durante un evento piovoso, avviene quando
l'energia dell'impatto della goccia \`e sufficiente a rompere le forze che
tengono insieme l'aggregato, e avviene in combinazione con gli altri
meccanismi \citep{al1982mechanism}.

La dispersione chimico fisica risulta dalla diminuzione delle forze
attrattive tra le particelle colloidali durante l'inumidimento
\citep{sumner1992electrical}.



\section{Sistemi agricoli a basso impatto ambientale}
Grazie alla rivoluzione verde avvenuta negli anni '50 del secolo
scorso, l'agricoltura ha sub\`ito un processo di trasformazione in cui
si è passati da una forma tradizionale ad una che fa
largo uso della tecnologia, oggi chiamata Convenzionale. L'agricoltura
Convenzionale esaspera il concetto di massimizzazione del rendimento
economico, \`e tecnologicamente orientata, utilizza ampie superfici
spesso coltivate a monocoltura (con conseguente perdita della
biodiversit\`a) e richiede ingenti quantit\`a di concimi e
fertilizzanti, normalmente di sintesi. Grazie alla rivoluzione verde,
la produzione agricola mondiale ha potuto fronteggiare il rapido e
gigantesco aumento della popolazione di met\`a '900
\citep{Ciuffoletti_2014}; ma, al tempo stesso, ha portato a problemi
di tipo ambientale e sanitario: patologie dovute all'esposizione dell'uomo ad
antiparassitari, alla riduzione della biodiversit\`a degli ecosistemi,
all'inquinamento di aria, suolo e acqua, alla desertificazione e
desertizzazione. Inoltre le coltivazioni intensive monovarietali hanno
facilitato la diffusione di patogeni, provocando gravi danni di tipo
economico agli agricoltori.

In risposta alle problematiche descritte, durante gli anni '70 sono
nati dei movimenti di agricoltori che cercavano di coltivare in modo
naturale eliminando fitofarmaci e concimi di sintesi. Da questi
movimenti inizia a prendere forma l'agricoltura Biologica che, ad
oggi, costituisce un'importante realt\`a dell'agricoltura mondiale. Si
stima infatti che, il 12\% della SAU italiana sia coltivata a
Biologico \citep{Bio_cifre}, in crescita.  Gli obiettivi che si
prefigge di raggiungere l'agricoltura Biologica sono:

\begin{itemize}
\item migliorare la biodiversit\`a e la stabilit\`a dell'agro-ecosistema;
\item evitare mezzi tecnici con impatto ambientale (locale e
  globale);
\item garantire una buona qualit\`a del prodotto.
\end{itemize}

Per raggiungere tali obiettivi, le aziende che aderiscono a questa
forma di agricoltura si impegnano a:

\begin{itemize}
\item escludere prodotti di sintesi;
\item utilizzare tecniche agronomiche idonee, piante resistenti
  e insetti predatori contro i parassiti (\emph{lotta biologica});
\item utilizzare tecniche di lavorazione non
  distruttive;
\item effettuare rotazioni colturali e
  sovesci;
\item utilizzare fertilizzanti naturali;
\item scegliere variet\`a, sementi e materiale vivaistico idonei a
  alla zona di coltivazione (intesa come insieme delle caratteristiche
  del terreno e del clima di una certa area) e ottimali per una
  determinata specie;
\item raccogliere i prodotti al momento ottimale di maturazione;
\item certificare sia il processo di produzione a garanzia del rispetto
  delle norme legislative che lo codificano che ogni singolo intervento
  lungo le differenti filiere produttive;
\item impiegare le tecniche e gli additivi di sola origine naturale
  per la preparazione e trasformazione degli alimenti.
\end{itemize}

Si suppone che l'applicazione di questi principi consenta il
mantenimento della fertilit\`a dei suoli: l'eliminazione dei pesticidi
comporterebbe una miglior salute della microfauna e microflora
tellurica, mentre l'impiego di sovesci e concimazioni organiche
porterebbe ad un aumento della sostanza organica nel terreno.


Mentre la produzione e l'impatto ambientale dell'agricoltura Biologica
sono stati ampiamente studiati, l'impatto sulle propriet\`a del suolo
non lo \`e stato altrettanto. Inoltre le conclusioni a cui arrivano i
pochi studi effettuati (quasi tutti a breve termine, ossia dalla
durata inferiore a 20 anni) danno risultati contrastanti
\citep{williams2017organic}.

\citet{siegrist1998does} affermano che la stabilit\`a degli aggregati
dei suoli in condzione Biologica sia maggiore rispetto a
quelli condotti Convenzionalmente, anche se i benefici dati
rispetto all'agricoltura Convenzionale non sono sufficienti a ridurre
l'erosione dovuta ad una pioggia molto intensa.

\citet{williams2017organic} sostengono che l'agricoltura Biologica
migliora le propriet\`a fisiche relative alla stabilit\`a degli
aggregati, alla compattazione del suolo e al drenaggio.

\citet{migliorini2014agronomic}, in un lavoro sul progetto MoLTE
\footnote{Montepaldi Long Term Experiment: l'esperimento a lungo
  termine attivo dal 1991 in cui \`e coinvolto anche questo studio
  (paragrafo \ref{sec:MOLTE})}, hanno riscontrato, a fronte di una
paragonabile produzione tra i due metodi di conduzione, un minor
surplus di azoto ed una miglior conservazione di carbonio e azoto a
lento rilascio (organico) in favore della conduzione Biologica.


\section{Progetto \emph{FertilCrop}}

FertilCrop (Fertility Building Management Measures in Organic Cropping
Systems) è un progetto europeo che prevede la collaborazione di venti
dipartimenti e istituti di ricerca, tra cui il Dipartimento delle
Scienze delle Produzioni Agroalimentari e dell'Ambiente (DISPAA)
dell'Universit\`a degli Studi di Firenze gi\`a impegnata
nell’esperimento di lungo termine MoLTE.

Lo scopo principale del progetto è quello di sviluppare delle tecniche
di gestione sostenibili ed efficienti per incrementare la
produttivit\`a nei sistemi agricoli biologici e si pone i seguenti
obiettivi:

\begin{enumerate}
\item studio dell’interazione spazio-temporale tra infestanti, sovesci
  e colture;
\item valutazione del ruolo della struttura e della porosit\`a degli
  orizzonti del suolo nella crescita delle colture e delle radici
  nell’assorbimento e perdita di nutrienti e negli scambi gassosi;
\item identificazione, analisi e miglioramento della comprensione
  dell’interazione pianta-microrganismi;
\item quantificazione e riesame delle variazioni nelle riserve di C e
  N e nella dinamica dei flussi di tali elementi;
\item calibrazione di modelli dinamici di flusso di C e N e di
  crescita delle piante in relazione alle pratiche che incrementano la
  fertilit\`a;
\item parametrizzazione di un modello di pianificazione strategica
  delle rotazioni colturali in relazione alla gestione della fertilit\`a
  del suolo;
\item sviluppo, in collaborazione con gli agricoltori, di strumenti e
  strategie per il riconoscimento visivo della fertilit\`a dei suoli.
\end{enumerate}

Il presente lavoro si inserisce nell'ambito di questo progetto con
l'intento di contribuire al raggiungimento dell’obiettivo 2, studiando
l’impatto di lavorazioni a diversa intensit\`a per mezzo di indicatori
di qualit\`a della struttura fisica del suolo.

\section{Scopo dello studio}
Lo scopo di questo lavoro è cercare la risposta ai seguenti due quesiti:
\begin{itemize}
\item dopo 25 anni di conduzione Biologica, sono cambiate le
  caratteristiche fisico-strutturali del terreno ?
\item tre diverse lavorazioni primarie quali aratura,
  rippatura e frangizollatura influenzano i parametri fisici del suolo ?
\end{itemize}

Per rispondere a queste due domande sono stati scelti degli indicatori
di fertilit\`a del suolo di natura fisica, quali la densit\`a
apparente, la distribuzione dei pori e la stabilit\`a degli aggregati.
Tali parametri sono stati misurati durante la stagione 2016-2017.


\chapter{Materiali e metodi}
\section{Descrizione del sito sperimentale}
\label{sec:MOLTE}
L'esperimento oggetto di questa tesi fa parte del progetto MoLTE
(Montepaldi Long Term Experiment) che è attivo dal 1991 nell’azienda
agricola dell’Universit\`a di Firenze (localit\`a Montepaldi, San
Casciano Val di Pesa) ed interessa una superficie leggermente declive
di circa \SI{15}{\hectare} a \SI{90}{\meter} s.l.m..



Il clima è sub-appenninico con precipitazioni totali di circa
\SI{800}{\milli\meter} annui con massimo in autunno e primavera e
minimo nel periodo tra giugno-agosto. La temperatura media annuale è
di \SI{14,1}{\celsius} con la massima che può superare i
\SI{30}{\celsius} in estate e la minima nel mese di gennaio che pu\`o
scendere sotto gli \SI{0}{\celsius}. Dal punto di vista pedologico
l’Azienda è caratterizzata da terreni evoluti su sedimenti pliocenici
di tipo conglomeratico misto a lenti sabbiose e argillose (aree
declivi) e da sedimenti del fiume Pesa risalenti all’Olocene (aree
pianeggianti) con caratteristiche tessiturali da essere definite tra i
\emph{medio impasto limo-argillosi} e gli \emph{argillosi} con
presenza variabile di scheletro di piccole e medie dimensioni.

\begin{figure}[ht]
  \centering
  \includegraphics[width=0.9\textwidth]{../foto/Panoramica_lavorazioni.jpeg}
  \caption{\label{fig:FotoPanoramaMpaldi} Veduta d'insieme dei campi sperimentali oggetto dello studio}
\end{figure}

Il sito sperimentale \`e costituito da due agroecosistemi, da qui in
avanti definiti come \emph{Conduzione}:
\begin{itemize}
\item conduzione Biologica\footnote{In realtà nell'azienda sono
    presenti due blocchi a conduzione Biologica: il primo \`e quello
    citato, ovvero il "Biologico vecchio", il secondo, non esaminato
    nel presente lavoro \`e denominato "Biologico nuovo"}, \emph{OO} (\emph{Old Organic})
\item conduzione \emph{Convenzionale}, \emph{CO}
\end{itemize}

I due agroecosistemi sono suddivisi in pi\`u appezzamenti
rettangolari (\SI{1.3}{\hectare} ciascuno),
identificati da sigle quali \emph{OO1, OO2, OO3, OO4} per il Biologico
vecchio e \emph{CO9, CO10} per il
Convenzionale (Fig. \ref{fig:foto_OO_sito}).

Nell'anno 2015-2016, sono stati campionati gli appezzamenti \emph{OO1, OO3, CO9, CO10},
mentre nell'anno 2016-2017 sono stati campionati \emph{OO2, OO4, CO9,
  CO10}

I due agroecosistemi sono circondati da infrastrutture ecologiche
quali siepi naturali e/o artificiali e/o strisce di essenze erbacee
spontanee. In particolare sono presenti due siepi: una naturale che
separa il Biologico vecchio da quello nuovo, costeggiata da entrambi i
lati da due strisce inerbite di 2 metri; l’altra artificiale,
piantata dal DISAT con l’aiuto del WWF agli inizi degli anni ’90,
separa gli appezzamenti a conduzione Biologica dagli altri campi
aziendali ed è formata da specie autoctone. Inoltre, una striscia
inerbita separa il sistema Biologico nuovo da quello
Convenzionale.


Dal 2001, sono state adottate le seguente rotazioni:
\begin{itemize}
\item per la conduzione Biologica
  \begin{enumerate}
  \item \small sovescio e coltura da rinnovo 
  \item \small cereale e leguminosa
  \item \small leguminosa 
  \item \small cereale
  \end{enumerate}
\item  per la conduzione Convenzionale
  \begin{enumerate}
    \item \small coltura da rinnovo
    \item \small cereale
  \end{enumerate} 
\end{itemize}

Nell'anno precedente ai campionamenti effettuati per questo studio, (2015), \`e
stato coltivato l'orzo negli appezzamenti \emph{OO2} e \emph{CO9} e il
girasole negli appezzamenti \emph{OO4} e \emph{CO10}.

In ogni appezzamento sono state messe a confronto le seguenti
lavorazioni primarie (\emph{Lavorazione}):
\begin{itemize}
\item aratura (\emph{Ara}),
\item rippatura (\emph{Rip}),
\item frangizollatura (\emph{Fzo}).
\end{itemize}

In pre-semina \`e stata effettuata una ulteriore frangizollatura per
tutti gli appezzamenti.

Ogni lavorazione \`e stata replicata tre volte per appezzamento che
diventa cos\`i suddiviso in 9 parcelle.


All'interno di ogni parcella sono stati individuati tre punti di
campionamento, partendo dal centro del campo
(Fig. \ref{fig:foto_OO_sito}): \emph{m} (medio), \emph{a} (alto, 4
metri sopra il medio) e \emph{b} (basso, 4 metri sotto il medio).



In totale sono stati raccolti 108 campioni di terreno, sia nell'anno
2015 che nell'anno 2016, principalmente le analisi hanno riguardato la
serie \emph{m}, quindi 36 campioni.

\begin{landscape}
\begin{figure}
 % \begin{minipage}{.5\linewidth}
  \centering
  \subfloat[Biologico]{
    \includegraphics[width=0.5\textwidth]{../foto/OO_sito.jpeg}
  }\quad
  \subfloat[Convenzionale]{
    \includegraphics[width=0.5\textwidth]{../foto/CO_sito.jpeg}
  }
  \caption[Diagramma degli appezzamenti a conduzione Biologica w
  Convenzionale]{Appezzamenti oggetto di studio. \emph{OO} seguito da un
    numero che indica l'appezzamento; la lettera maiuscola indica la
    lavorazione \emph{A}(aratura), \emph{B}(rippatura),
    \emph{C}(frangizollatura); il numero (\emph{1, 2, 3}) indica la
    riga; la lettera minuscola indica la replica all'interno del plot
    (\emph{a} alto, \emph{m} medio, \emph{b} basso). Il fiume Pesa si
    trova sul margine inferiore dello schema e la collina su quello
    superiore}
  \label{fig:foto_OO_sito}
%   \end{minipage} %
\end{figure}
\end{landscape}
% \begin{figure}
%   \centering
%   \includegraphics[width=0.75\textwidth]{../foto/CO_sito.jpeg}
%   \caption[Diagramma degli appezzamenti a conduzione
%   Convenzionale]{Appezzamenti Convenzionale, la codifica segue quella
%     descritta per l'appezzamento Biologico}
%   \label{fig:foto_CO_sito}

% \end{figure}

\section{Misura della densit\`a apparente}
La densit\`a apparente del suolo è stata misurata sia con il metodo
\emph{Core} (utilizzando grandi volumi) che con il metodo \emph{Clod}
(utilizzando piccoli aggregati) \citep{black1900method}.

\subsection{Metodo \emph{Core}}%Densimetria per grandi volumi (cilindro)}
Per misurare la densit\`a apparente del suolo con il metodo
\emph{Core}, sono stati prelevati dei campioni
di terreno mediante l'utilizzo di un cilindro non deformabile di
volume noto (Fig. \ref{fig:cilindro}).


\begin{figure}[ht]
  \centering
  \includegraphics[width=0.5\textwidth]{../foto/cilindroOttone.jpeg}

  \caption[Cilindro in ottone usato per la misura della densità
  apparente: metodo \emph{Core}]{Cilindro in ottone utilizzato per
    prelevare i campioni da destinare all'analisi di densit\`a
    apparente col metodo \emph{Core}.}
  \label{fig:cilindro}
\end{figure}
\FloatBarrier


Il cilindro \`e stato inserito nel suolo per tutta la sua lunghezza e
quindi estratto facendo attenzione che il materiale al suo interno non
fuoriuscisse in modo da formare due superfici piatte sulle basi del cilindro.
Il campione prelevato, portato in laboratorio, \`e stato passato a
umido attraverso un vaglio con fori circolari a \SI{2}{\milli\metre}
di diametro. Il volume dello scheletro rimasto nel vaglio \`e stato
misurato successivamente per spinta idrostatica.  Il suolo vagliato
\`e stato essiccato in stufa a \SI{105}{\celsius} fino a peso
costante, e successivamente pesato \citep{ugolini2010basi}.

\begin{figure}[ht]
  \centering
  \includegraphics[width=0.7\textwidth]{../foto/secco.jpeg}
  \caption{Metodo \emph{Core}: il terreno dopo essicazione in stufa}
  \label{fig:FotoSeccoCore}
\end{figure}
\FloatBarrier

Con i dati ottenuti, \`e stato ricavato il valore della densit\`a
apparente ($rho_{CoreApp}$) tramite la seguente formula:

\begin{equation}
  \label{eq:DensitaApparente}
  \rho_{CoreApp}=\frac{P_{secco}}{V_{cilindro}-V_{scheletro}}
\end{equation}

Dove:\\
\begin{tabular}{rp{12cm}}
  $V_{cilindro}$=       & volume del cilindro di ottone (\SI{854.1}{\cubic\centi\metre}); \\
  $V_{scheletro}$=    & volume dello scheletro (>\SI{2}{\milli\metre}) misurato per spinta
                        idrostatica (\SI{}{\cubic\centi\metre}); \\
  $P_{secco}$=       & peso del terreno vagliato
                       (<\SI{2}{\milli\metre}) ed essiccato a
                       \SI{105}{\degree} (\SI{}{\kilogram}).
\end{tabular}
\vspace*{3em}



\subsection{Metodo \emph{Clod}}%Densimetria per piccoli aggregati (petrolio)

A differenza del metodo \emph{Core}, questa misura viene effettuata su
aggregati di piccole dimensioni (3-\SI{4}{\cm} di diametro).  Il
metodo \emph{Clod} viene anche detto metodo per spinta idrostatica
\citep{Monnier_1973}. La procedura consiste nel mantenere a bagno nel
petrolio per una notte degli aggregati di terreno
(Fig. \ref{fig:petrolio}) cercando di ridurre al minimo le
manipolazioni per mantenere la struttura dell'aggregato stesso.

\begin{figure}[ht]
  \centering
  \includegraphics[width=0.7\textwidth]{../foto/petrolio.jpeg}
  \caption{metodo \emph{Clod}: aggregati immersi in petrolio per la
    misura della densità apparente}
  \label{fig:petrolio}
\end{figure}
\FloatBarrier


Successivamente gli aggregati (completamente imbevuti di petrolio)
vengono asciugati con carta fino a "brillantezza", in modo che
solo una pellicola di liquido avvolga il campione. Per misurare la
spinta idrostatica \`e stato posto sul piatto di una bilancia
(sensibilit\`a $\pm 10^{-3}$\SI{}{\gram}), un contenitore riempito di
petrolio nel quale era immersa una navicella di rete forata, mantenuta
sospesa da un supporto metallico. Dopo aver misurato la tara, \`e
stato posto il campione entro la navicella (Fig. \ref{fig:bilancia}) e
quindi \`e misurato il peso del petrolio spostato.

\begin{figure}[ht]
  \centering
  \includegraphics[width=0.7\textwidth]{../foto/navicella.jpeg}
  \caption{Metodo \emph{Clod}: disposizione della bilancia per la
    misura della spinta idrostatica}
  \label{fig:bilancia}
\end{figure}
\FloatBarrier
Per il principio di Archimede, il peso misurato \`e uguale al peso del
volume di petrolio spostato; da questa informazione \`e stato
possibile calcolare al volume del campione applicando la seguente
formula:

\begin{equation}
  \label{eq:VolumeAggr}
  V_{totale}=\frac{S_{totale}}{D_{petrolio}}
\end{equation}

Dove:\\
\begin{tabular}{rp{12cm}}
  $V_{totale}$= & volume dell'aggregato comprendente il volume del
                  solido e il volume dei vuoti (\SI{}{\cubic\cm});\\
  $S_{totale}$=  &  spinta idrostatica
                     dell'aggregato imbevuto di petrolio (\SI{}{\gram});\\
  $D_{petrolio}$=  &  densit\`a del petrolio utilizzato per
                     l'analisi (\SI{0.761}{\gram\per\cubic\cm}).
\end{tabular}


Successivamente il campione \`e stato essiccato per una notte a
\SI{150}{\degreeCelsius} quindi \`e stato pesato\footnote{Il
  raggiungimento di questa temperatura consente di allontanare l'acqua
  di idratazione dei cationi di scambio bivalenti (Ca, Mg) degli
  interstrati dei minerali a reticolo espandibile
  \citep{Monnier_1973}}. Il peso misurato \`e quello della sola fase
solida.


La densit\`a reale \`e si ottiene da:

\begin{equation}
  \label{eq:densitapetrolio}
  \rho_{ClodApp} = \frac{P_{150}}{V_{totale}}
\end{equation}

Dove:\\
\begin{tabular}{rp{12cm}}
  $\rho_{ClodApp}$=  & valore della densit\`a apparente dell'aggregato
                      misurato (\SI{}{\gram\per\cubic\cm});\\
  $P_{150}$=       & peso dell'aggregato essiccato a
                     \SI{150}{\celsius} (\SI{}{\gram});\\
  $V_{totale}$=  & volume calcolato con la formula
                      \ref{eq:VolumeAggr}  (\SI{}{\cubic\cm}).
\end{tabular}




\section{Dinamica della distribuzione della dimensione degli aggregati}
La dinamica di disgregazione degli aggregati di suolo \`e stata
indagata per mezzo dello strumento Mastersizer 2000 \citep{Mas_2000}.
Il Mastersizer 2000 \`e mostrato in Fig. \ref{fig:DisegnoMsizer2000}
nella cui didascalia vengono descritti i dettagli.
\begin{figure}[ht]
  \centering
  \includegraphics[width= 0.7\textwidth]{../foto/mastersizer.jpeg}
  \caption[Schema dello strumento Mastersizer 2000, utilizzato per
  misurare la stabilità degli aggregati]{Schema dello strumento
    Mastersizer 2000, immagine tratta dal manuale utente. 1) un tavolo
    ottico, che colleziona i dati i quali verranno usati per calcolare
    la dimensione delle particelle del campione; 2) una unit\`a di
    dispersione del campione, che ha lo scopo di disperdere il
    campione in acqua e condurlo al tavolo ottico tramite una pompa, per effettuare la misura laser;
    3) un elaboratore su cui è installato il software apposito che
    analizza i dati grezzi per determinare la dimensione delle
    particelle.}
  \label{fig:DisegnoMsizer2000}
\end{figure}
\FloatBarrier Per rompere totalmente gli aggregati, viene utilizzato
un emettitore di ultrasuoni presente nel Mastersizer 2000.

La presenza di una pompa e di un agitatore sono necessari per
consentire il ricircolo della sospensione di suolo e acqua e la
corretta lettura della sua torbidit\`a. Nel nostro caso l'applicazione
dell'energia cinetica al campione dovuta al ricircolo dell'acqua, \`e tenuta in considerazione
per la determinazione della resistenza alla disgregazione
degli aggregati. Infatti viene effettuata una lettura a intervalli regolari
(quindi analizzando la variazione della distribuzione nel tempo) viene
determinata la capacit\`a degli aggregati di resistere alle
sollecitazioni prima della sonicazione


\subsection{Protocollo di misura}
Per la preparazione del campione da misurare, \`e stata separata una
aliquota di suolo dal campione talquale la cui dimensione delle
particelle \`e compresa tra 1 e \SI{2}{\milli\meter}; successivamente
\`e stata messa a seccare a \SI{40}{\celsius} per una notte.  Prima
della misurazione effettiva del campione \`e stato necessario misurare
un "bianco" per acquisire l'intensit\`a della radiazione luminosa
all'ingresso del campo delle particelle, $I_0$
(Eq. \ref{eq:BeerLambert} pagina \pageref{eq:BeerLambert}). Da questa
aliquota, \SI{300}{\mg} sono stati immessi nell'unit\`a di dispersione
del campione opportunamente riempita di acqua.  

Lo strumento effettua una misurazione della distribuzione
granulometrica ogni minuto, per 12 minuti.  Dopo il \SI{12}{\degree}
minuto, per completare la rottura degli aggregati, viene attivata la
sonicazione.

Per valutare il fenomeno dello \emph{slaking}, ogni misurazione \`e
stata ripetuta due volte: una sul campione secco e una sul campione
precedentemente inumidito con acqua demineralizzata.

\subsection{Dinamica della distribuzione granulometrica}
A conclusione della misura abbiamo ottenuto, per le 36 combinazioni dei
fattori dell'esperimento, 24+24 distribuzioni granulometriche:
\begin{itemize}
  \item 24 per ogni campione secco di cui:
  \begin{itemize}
    \item 12 distribuzioni dal minuto 1 al minuto 12 senza sonicatura;
    \item 12 distribuzioni dal minuto 13 al minuto 24 con la sonicatura attiva;
  \end{itemize}
  \item 24 per ogni campione umido di cui
    \begin{itemize}
      \item 12 distribuzioni dal tempo 1 al tempo 12 senza sonicatura;
      \item 12 distribuzioni dal minuto 13 al minuto 24 con la sonicatura attiva.
    \end{itemize}
\end{itemize}

% \begin{figure}[ht]
%   \centering
%   \includegraphics[width=0.8\textwidth]{../foto/distropisa.jpeg}
%   \caption[Esempi di curve di distribuzione granulometrica
%   dinamica]{Alcuni esempi di curve di distribuzione
%     granulometrica dei campioni 25, 28, 13, 17, 1, 10. Sull'asse delle ascisse
%     in scala logaritmica sono presenti i valori dei diametri delle varie particelle 
%     misurate dallo strumento in \SI{}{\micro\metre}; sull'asse
%     delle ordinate sono presenti i relativi valori in
%     percentuale.}
% \end{figure}
% \FloatBarrier

\section{Porosimetria per intrusione di mercurio}
Le misure della distribuzione dei pori sono state realizzate
rispettivamente: con un porosimetro Carlo Erba serie 2000 per i
macropori e un porosimetro PASCAL 140 per i micropori, entrambi
collegati ad un elaboratore DOS per la raccolta e per una prima
elaborazione dei dati \citep{LuigiTesi}.

\begin{figure}[ht]
  \centering
  \includegraphics[width=0.7\textwidth]{../foto/porosimetri.jpeg}
  \caption{A sinistra il porosimetro PASCAL 140 utilizzato per la misura
    dei micropori, a destra il porosimetro Carlo Erba series 2000 per
    la misura dei macropori. \label{fig:porosimetri}}
\end{figure}
\FloatBarrier La misura viene effettuata per i pori nell'intervallo di
diametro compreso tra circa \SI{5}{\micro\meter} a circa
\SI{2000}{\micro\meter}.

Gli aggregati di circa un grammo vengono introdotti in un contenitore di
vetro speciale (dilatometro) esso ha nella base un contatto elettrico
con terminazione interna ed esterna, superiormente \`e chiuso da un
cono a smeriglio che si prolunga in un capillare calibrato di
\SI{6}{\mm} di diametro e lungo \SI{10}{\centi\meter}.

Il dilatometro contenente il campione viene inserito nel circuito del
vuoto dall'unit\`a macropore; dopo la stabilizzazione del vuoto esso
viene lentamente riempito (\SI{15}{\centi\meter\cubed}) con mercurio
fino a raggiungere una pressione idrostatica, valutata dal baricentro
del campione, di circa \SI{35}{\torr}. Questo livello consente di
seguire, traguardandomne otticamente il menisco, l'intrusione di
mercurio nell'intervallo 0-\SI{1}{\atm}, realizzato per progressiva
immissione di aria esterna. La scelta di questo valore di pressione
idrostatica del mercurio consente di seguire il livello del menisco in
tutto l'intervallo di intrusione dei campioni. Questa scelta limita a
circa \SI{2000}{\micro\meter} il valore massimo del diametro dei pori
misurabile.

Per valutare i pori pi\`u piccoli si introduce il dilatometro, previo
riempimento del capillare, nell'autoclave del Porosimetro PASCAL
140. Una pompa idraulica collegata ad un moltiplicatore di pressione
realizza all'interno, tramite un olio dielettrico, una pressione fino
a \SI{2000}{\atm}; incrementi di pressione possono essere regolati da
un'unit\`a di controllo; naturalmente pi\`u \`e lenta l'intrusione
migliore \`e la distribuzione delle dimensioni dei pori.

La progressiva penetrazione di mercurio nel campione \`e acquisita
tramite un sensore capacitivo. Il segnale elettrico che ne deriva
viene convertito in volume di mercurio intruso. Il calcolo della
distribuzione dei pori, mediante l'equazione di Washburn
(eq. \ref{eq:Washburn}, pagina \pageref{eq:Washburn}), viene effettuata dopo la sottrazione
automatica punto per punto dei valori legati alla compressibilit\`a di
mercurio preventivamente calcolati in un ciclo di misura senza
campioni. Alla fine del ciclo di intrusione, l'apparecchio va
automaticamente in depressione.


% \subsection{Protocollo di misura}


\section{Elaborazione dei dati}

I dati sono stati analizzati mediante il linguaggio di programmazione
ad oggetti R 3.4.0 \citep{r_programming}.  L'esplorazione dei modelli
statistici \citep{fox2002r, chambers1992statistical, faraway2004} è
stata fatta mediante confronto di modelli statistici marginali e un
test F ($\textrm{p < 0,05}$).  Tutti i modelli statistici sono stati
validati attraverso l'analisi esplorativa dei residui (appendice \ref{sec:residui}) in modo da
verificare le eventuali violazioni delle assunzioni di normalit\`a
\citep{stefanini2007introduzione}.

\subsection{Densit\`a}
I risultati delle analisi sia con il metodo \emph{Core} che con il metodo \emph{Clod} non hanno
riscontrato interazioni statisticamente significative tra i parametri
considerati e quindi esse non compaiono nei modelli statistici sotto riportati,
che sono quindi di natura additiva.

\`E stato quindi adattato il seguente modello statistico:

\begin{modello}
  \label{mod:MetodoClod}
  Y \sim \mu + \beta_1x_1 + \beta_2x_2 + \beta_3x_3 + \epsilon
\end{modello}

dove: \\

\begin{tabular}{rp{12cm}}
  $\beta_1 =$ & \emph{Anno}, due livelli: \emph{2015, 2016};\\
  $\beta_2 =$  & \emph{Conduzione}, due livelli: \emph{Convenzionale, Biologico};\\
  $\beta_3 =$ & \emph{Lavorazione}, tre livelli: \emph{Arato, Rippato, Frangizollato};\\
  $\epsilon =$ & residui o errore.
\end{tabular}
\vspace*{3em}


La variabile categorica \emph{anno}, \`e stata necessariamente
eliminata dal modello per il metodo \emph{Clod}, per la mancata
disponibilità dei dati per l'anno 2015.

Una volta ottenuto il modello definitivo \`e stata effettuata
un'analisi della varianza (ANOVA) sul modello.

Infine, data la natura additiva dei modelli statistici, ai gruppi oggetto dello
studio, \`e stato applicato il test di Tukey-Siegel utilizzando le
librerie 'agricolae' \citep{agricolae} e 'multcomp' \citep{multcomp}.


\subsection{Dinamica della distribuzione degli aggregati e porosimetria}

I dati provenienti da queste due analisi sono, per loro stessa natura,
composizionali e quindi sono stati analizzati con la libreria
'composition' \citep{compositional}.  Le distribuzioni ricavate dagli
strumenti, infatti, sono espresse come valore percentuale sul totale;
questi sono stati raggruppati in tre classi dimensionali
(macroaggregati, mesoaggregati, microaggregati e macropori, mesopori,
micropori). I limiti delle tre classi dimensionali sono state definiti
in base alla classificazione della letteratura (\cite{paul2014soil},
\cite{tisdall1982organic}, \cite{greenland1977soil},
\cite{lal2004principles}).

A questo punto \`e stato adattato il modello statistico all'interno
dello spazio vettoriale del simplesso
(appendice \label{sec:composizionale}) e, dopo l'esplorazione visuale
della normalit\`a dei residui (appendice \ref{sec:residui}),
verificata la significativit\`a dei trattamenti mediante l'ANOVA.


\chapter{Risultati}
\section{Densit\`a apparente}

<<ImportDensCampo, eval=TRUE, echo=FALSE>>=
df.dueAnni <-
read.table(file.path(DirElab, "df_dueanni.csv"),
header = T, sep = "")
df.dueAnni <-  df.dueAnni[df.dueAnni$REPLICA == "m", ]

##with(df.dueAnni, table(YEAR, TRT,LAVORAZIONE, APPEZZAMENTO))
## df.dueAnni <-
## read.table(file.path(DirElab, "dens_app.csv"),
## header = T, sep = ";")
df.dueAnni <- df.dueAnni[df.dueAnni$REPLICA== "m",]
###################################################
###DescrittivaDensitaCampo1
###################################################
##with(df.dueAnni, table(TRT, LAVORAZIONE, APPEZZAMENTO, YEAR))
options(contrasts=c("contr.treatment","contr.poly"))

fattore <- interaction(df.dueAnni$YEAR, df.dueAnni$TRT, df.dueAnni$LAVORAZIONE)
amod <- aov(densita.apparente ~ fattore, data=df.dueAnni)
HSD.test(amod, "fattore", group=TRUE, alpha = 0.05)
tuk <- glht(amod, linfct = mcp(fattore = "Tukey"))
tuk.cld<- cld(tuk)
summary.campo <-
data.frame(
aggregate(densita.apparente ~ YEAR+TRT+LAVORAZIONE,
data = df.dueAnni,
function(x){round(mean(x, na.rm=TRUE),2)}),
ST.DEV=
aggregate(densita.apparente ~ YEAR+TRT+LAVORAZIONE,
data = df.dueAnni,
function(x){round(sd(x, na.rm=TRUE),2)})[,4],
n= aggregate(densita.apparente ~ YEAR+TRT+LAVORAZIONE,
data = df.dueAnni,
function(x){sum(!is.na(x))})[,4],
Tukey  = as.vector(tuk.cld$mcletters$Letters)
)
##names(summary.campo)[4] <- "Dens.app.g.cmc"
attach(summary.campo)
summary.campo <-
summary.campo[order(YEAR, TRT, LAVORAZIONE),]
detach(summary.campo)
@

\subsection{Metodo \emph{Core}}

La tabella \ref{tab:summaryCore} riassume i dati ottenuti calcolando
la densit\`a apparente (formula \ref{eq:DensitaApparente}, pagina
\pageref{eq:DensitaApparente}). La figura \ref{fig:boxplotCore} riporta gli stessi dati in
forma grafica. I valori, la cui media generale \`e pari a
\SI{\Sexpr{round(mean(df.dueAnni$densita.apparente,na.rm=TRUE),2)}}{\gram\per\cubic\centi\metre},
sono simili a quelli che pi\`u frequentemente si riscontrano nel
suolo.


<<Summary_Campo, echo=FALSE, eval=TRUE, results=tex>>=
names(summary.campo) <-  
c("Anno", "Conduzione", "Lavorazione", "Media", "Dev. std", "n", "Tukey")
summary.campo$Anno <- 
c("2015", rep(" ", 5), "2016", rep(" ", 5))
summary.campo$Conduzione <-
c("Convenzionale", rep(" ", 2), "Organico", rep(" ", 2),
"Convenzionale", rep(" ", 2), "Organico", rep(" ", 2))
summary.campo$Lavorazione <- 
    mapvalues(summary.campo$Lavorazione, from = c("Ara", "Rip", "Fzo"), to = c("Arato", "Rippato", "Frangizollato"))
tabella.campo <-
xtable(summary.campo[,-7],
label = 'tab:summaryCore', align  = "llllccc",
caption =
"Valori medi della densit\\`a apparente (in \\SI{}{\\gram\\per\\cubic\\centi\\metre}),
suddivisi per \\emph{Anno}, \\emph{Conduzione} e \\emph{Lavorazione} " )
print(tabella.campo, include.rownames=FALSE,
caption.placement = "top",
table.placement= "hb")

@
\FloatBarrier



<<label = ResiduiCampo, echo=FALSE, fig = TRUE, include = FALSE>>=
limiti.x <- c(0,13)
limiti.y <- c(1, 1.8)
plot(1, xlim = limiti.x, ylim = limiti.y, type = "n",
yaxt = "n", xaxt = "n", xlab = "", ylab = "", main = "Metodo Core")
mtext(expression(paste("Densit\`a apparente g ", cm^-3)),
side = 2, line = 2)
rect(0.25,1, 3.45,1.8, col = "lightgray", border = NA)
rect(3.55,1, 6.5,1.8, col = "gray", border = NA)
rect(6.5,1, 9.45,1.8,col = "lightgray", border = NA)
rect(9.55,1, 12.75,1.8,col = "gray", border = NA)
rect(0.25,1, 6.5,1.8,lwd = 2)
rect(6.5,1, 12.75,1.8,lwd = 2)
abline(h = 2.65/2, col = 2)
with(df.dueAnni,
boxplot(densita.apparente ~ LAVORAZIONE+TRT+YEAR,
las = 2, xaxt = "n",
col = c(2,3,4), add = TRUE)
)
text(3.5, 1.8, "Anno 2015", pos = 1, cex = 2)
text(9.5, 1.8, "Anno 2016", pos = 1, cex = 2)
legend(9.3, 1.2,
c("Arato","F.zollato","Rippato"),
box.col = "transparent",
fill=c(2,3,4), cex=1,  ncol = 1)
## points(y = jitter(rep(1:12, each = 6), 0.5),
##        x = unlist(split(densita.apparente, interaction(LAVORAZIONE, TRT, YEAR))),
##        cex = 2, pch = 4)
text( 2, 1.7, "CO", pos = 1, cex = 1.5)
text( 5, 1.7, "OO", pos = 1, cex = 1.5)
text( 8, 1.7, "CO", pos = 1, cex = 1.5)
text(11, 1.7, "OO", pos = 1, cex = 1.5)
@

\begin{figure}[hb]
  \centering
  % <<label=figboh2, fig=TRUE, echo=FALSE, width=5.4, height=5.4 >>=
  % <<ResiduiCampo>>
  % @
  \includegraphics[width=\textwidth]{Tesi_GIT-figboh2.pdf}

  \caption[Boxplot della densit\`a apparente: metodo
  \emph{Core}]{Boxplot della densit\`a apparente misurata con il metodo \emph{Core}
    relativi alla conduzione (\emph{Convenzionale} e \emph{Biologico}) e per le varie
    lavorazioni (\emph{Arato, Frangizollato} e \emph{Rippato}). La riga rossa indica
    la media generale}
  \label{fig:boxplotCore}
\end{figure}
\FloatBarrier

<<ModelloDensitaCampo, echo=FALSE, eval=TRUE, results=tex>>=
lm.Densita <-
    lm(densita.apparente ~ YEAR+TRT+LAVORAZIONE, data = df.dueAnni)
lm.DensSign <-
    lm(densita.apparente ~ YEAR+TRT, data = df.dueAnni)
@

%% Il modello utilizzato, (\ref{mod:MetodoClod}, pag.
%% \pageref{mod:MetodoClod}). \`E stato costruito un modello additivo in
%% quanto non sono state trovate interazioni statisticamente
%% significative tra l'anno, la \emph{Conduzione} e la \emph{Lavorazione}

%% \migliora[inline]{riscrivere}

La tabella \ref{tab:anova del modello} riporta l'ANOVA del modello
statistico e indica la non significatività dei trattamenti presi in
esame.

<<anova_modello, echo=FALSE, eval=TRUE, results=tex>>=
anova.dens <- anova(lm.Densita)
rownames(anova.dens) <-     c("Anno", "Conduzione", "Lavorazione", "residui")
##%   c("Anno", "Management", "Tillage", "residui")
tabella.anova.dens <-
xtable(anova.dens,
label = 'tab:anova del modello', align  = "lrrrrr",
caption = 'Tabella ANOVA per i valori di densità rilevati col metodo \\emph{Core}')
print(tabella.anova.dens,
include.rownames=TRUE,
caption.placement = "top")
@
\FloatBarrier

% 8rino revisionare \newline Da questa \`e possibile
% confermare ci\`o che \`e stato mostrato dall'analisi visuale,
% ovvero: il terreno degli appezzamenti condotti a Biologico \`e
% mediamente pi\`u denso di quello degli appezzamenti condotti a
% Convenzionale. Inoltre l'anno 2015 presenta delle densit\`a
% apparenti pi\`u alte rispetto all'anno 2016.}



<<Summary_modello2, echo=FALSE, eval=FALSE, results=tex>>=

sommario.dens <- 
    round(summary(lm.DensSign)$coefficients, 3)

rownames(sommario.dens) <-
c("CO 2015", "Scostamento 2016", "Scostamento OO")
sommario.dens[,4] <- round(sommario.dens[,4],2)
sommario.dens[1,4] <- "<10^-3"
tabella.summary.dens <-
xtable(sommario.dens,
label = 'tab:t-table del modello2', align  = "lrrrr",
caption = '')

print(tabella.summary.dens,
include.rownames=TRUE,
caption.placement = "top")
@


<<label = boxplot2, echo=FALSE, eval = FALSE, fig=TRUE, include = FALSE>>=
fattore <- interaction(df.dueAnni$YEAR, df.dueAnni$TRT)
amod <- aov(densita.apparente ~ fattore, data=df.dueAnni)
HSD.test(amod, "fattore", group=TRUE, alpha = 0.05)
tuk <- glht(amod, linfct = mcp(fattore = "Tukey"))
tuk.cld<- cld(tuk)   #letter-based display
posiz.y <- 1.7
## tapply(df.dueAnni$BD.g.cmc,
##             fattore,
##           function(x) mean(x, na.rm = TRUE)
##         )
limiti.x <- c(0,5)
limiti.y <- c(1, 1.8)
plot(1, xlim = limiti.x, ylim = limiti.y, type = "n",
yaxt = "n", xaxt = "n", xlab = "",ylab = "", main = "Metodo Core")
##mtext(expression(paste("Densit\`a apparente g ", cm^-3)), side = 2, line = 2)
rect(0.25,1, 2.45,1.8, col = "lightgray", border = NA)
rect(2.48,1, 4.75,1.8, col = "gray", border = NA)
rect(0.25,1, 2.45,1.8,lwd = 2)
rect(2.48,1, 4.75,1.8,lwd = 2)
with(df.dueAnni,
boxplot(densita.apparente ~ YEAR + TRT, ### ATTENZIONE A NON INVERTIRE TRT con YEAR !!
las = 2, xaxt = "n",
col = c(5, 6), add = TRUE))
mtext(expression(paste("Densit\`a apparente g ", cm^-3)), side = 2, line = 2)
text(1.5, 1.8, "Anno 2015", pos = 1, cex = 1.5)
text(3.5, 1.8, "Anno 2016", pos = 1, cex = 1.5)
text(x = 1:4, y = posiz.y, tuk.cld$mcletters$Letters, cex = 1.5, col = "red")
legend(3, 1.2,
c("Convenzionale", "Biologico"),
box.col = "transparent",
fill=c(5,6), cex=0.8,  ncol = 1)
##points(y = jitter(rep(1:12, each = 6), 0.5),
##x = unlist(split(densita.apparente, interaction(LAVORAZIONE, TRT, YEAR))),
##cex = 2, pch = 4)
@


<<label = qqplotCampo, fig.width=0.8, fig.height=0.8, echo=FALSE, eval = TRUE, fig=TRUE, include = FALSE>>=
par(mfrow = c(2,2))
plot(lm.Densita)
@ 

\subsection{Metodo \emph{Clod}}

<<importa_petrolio, echo=FALSE, eval=TRUE>>=
df.petrolio <-
read.table(file.path(DirElab, "df_spinta.csv"),
header = T, sep = "")
fattore <- with(df.petrolio, interaction(TRT, LAVORAZIONE))
amod <- aov(df.petrolio$densita.apparente ~ fattore)
HSD.test(amod, "fattore", group=TRUE, alpha = 0.05)
tuk <- glht(amod, linfct = mcp(fattore = "Tukey"))
tuk.cld <- cld(tuk) #letter-based display)
summary.petrolio <-
data.frame(
aggregate(densita.apparente ~ TRT+LAVORAZIONE,
data = df.petrolio,
function(x){round(mean(x, na.rm=TRUE),2)}),
ST.DEV=
aggregate(densita.apparente ~ TRT+LAVORAZIONE,
data = df.petrolio,
function(x){round(sd(x, na.rm=TRUE),2)})[,3],
n= aggregate(densita.apparente ~ TRT+LAVORAZIONE,
data = df.petrolio,
function(x){sum(!is.na(x))})[,3],
Tukey =     as.vector(tuk.cld$mcletters$Letters)
)

##names(summary.campo)[4] <- "Dens.app.g.cmc"
attach(summary.petrolio)
summary.petrolio <- summary.petrolio[order(TRT, LAVORAZIONE),]
detach(summary.petrolio)
names(summary.petrolio) <- c("Conduzione","Lavorazione","Media","Dev. std", "n", "Tukey")
summary.petrolio$Conduzione <- c("Convenzionale", rep("", 2), "Organico", rep("", 2))
summary.petrolio$Lavorazione <- mapvalues(summary.petrolio$Lavorazione, from = c("Ara", "Rip", "Fzo"),
                                          to = c("Arato", "Rippato", "Frangizollato"))
@ 

Il metodo \emph{Clod} ha permesso, grazie alla sua speditivit\`a, di
analizzare tutte le 108 combinazioni dei fattori dell'esperimento:
per ogni combinazione sono stati analizzati tre campioni. La media dei
tre campioni è stata usata per l'analisi dei dati.
I valori della densit\`a apparente calcolati mediante l'equazione
\ref{eq:densitapetrolio} sono mediamente pi\`u elevati (media;
\Sexpr{round(mean(df.petrolio$densita.apparente, na.rm=T),2)})
rispetto a quelli ottenuti utilizzandi il metodo \emph{Core} riportati a
pag. \pageref{tab:summaryCore}.


<<Sommario_petrolio, echo=FALSE, eval=TRUE, results=tex>>=
tabella.petrolio <-
xtable(summary.petrolio,
label = 'tab:summaryClod', align  = "lllcccc",
caption =
"Valori medi della densit\\`a apparente (in
\\SI{}{\\gram\\per\\cubic\\centi\\metre}),
relativi al tipo di conduzione e lavorazione " )
print(tabella.petrolio, include.rownames=FALSE, caption.placement = "top")
@

In tabella \ref{tab:summaryClod} \`e riportata l'ANOVA dei dati di densit\`a apparente 
relativi al tipo di conduzione. In Fig. \ref{fig:boxplotClod}
\`e riportato il boxplot.


<<label = boxplotpetr, fig.width=0.8, fig.height=0.8, echo=FALSE, fig = TRUE, include = FALSE>>=

with(data = df.petrolio,
{
  plot(1, xlim = c(0.5, 6.5), ylim = c(1.4, 2.5), type = "n",
  yaxt = "n", xaxt = "n", xlab = "",ylab = "")
  rect(0.5, 1.4, 3.45,2.5, col = "lightgray", border = NA)
  rect(3.48,1.4, 6.5,2.5, col = "gray", border = NA)
  boxplot(jitter(densita.apparente) ~ LAVORAZIONE+TRT, col = c(2,3,4),
  main = "Metodo Clod",
  ##xlab = "Densità apparente",
  las = 1, xaxt = 'n',
  ylim = c(1.5, 2.3),
  yaxs = "i",
  add=TRUE
  )
  ##axis(1, labels = FALSE)
  ##etichette <- levels(interaction(LAVORAZIONE,TRT))
  ## Plot x labs at default x position
  ##text(x =  seq_along(etichette), y = 1.3,
  ##srt = 45, adj = 1,
  ##labels = etichette, xpd = TRUE)
  mtext(expression(paste("Densità apparente g ", cm^-3)), side = 2, line = 2)
  text(2, 2.3, "CO", pos = 3, cex = 2)
  text(5, 2.3, "OO", pos = 3, cex = 2)
  ## points(y = jitter(rep(1:6, each = 22), 0.5),
  ##   x = unlist(split(densita.apparente, interaction(LAVORAZIONE, TRT))),
  ##   cex = 2, pch = 4)
  
  legend(4.5, 1.7,
  c("Arato","F.zollato","Rippato"),
  box.col = "transparent",
  fill=c(2,3,4), cex=1,  ncol = 1)
}
)

@

\begin{figure}[ht]
  \centering
<<label=figmah, fig=TRUE, echo=FALSE, width = 5.4, height  = 5.4 >>=
<<boxplotpetr>>
@
  \caption[Boxplot dei valori di densit\`a apparente: metodo \emph{Clod}
  ]{Boxplot dei valori di densit\`a apparente dei campioni misurati col metodo di
    analisi \emph{Clod}; gli appezzamenti condotti convenzionalmente (a
    sinistra) hanno valori più alti degli appezzamenti
    condotti a Biologico (a destra)}
  \label{fig:boxplotClod}

\end{figure}
\FloatBarrier

La tabella \ref{tab:anova piccoli aggregati} indica che entrambi i
fattori sono statisticamente significativi. Avendo verificato
l'assenza di interazioni tra \emph{Conduzione} e \emph{Lavorazione}
(vedi pag. \pageref{mod:MetodoClod}) è quindi stato effettuato un test
di Tukey-Siegel.

<<Analisi_Petrolio, echo=FALSE, eval=TRUE>>=
lm.spinta <-
lm(densita.apparente ~ TRT + LAVORAZIONE, data = df.petrolio)

anova_spinta <-
anova(lm.spinta)

summary_spinta <-
summary(lm.spinta)
@

<<Analisi_Petrolio, echo=FALSE, eval=TRUE, results=tex>>=
rownames(anova_spinta) <- c("Conduzione", "Lavorazione", "Residui")
tabella.spinta.anova <-
xtable(anova_spinta,
label = 'tab:anova piccoli aggregati', align = 'lrrrrr',
caption = ' Tabella ANOVA per i valori di densit\\`a misurati con il metodo \\emph{Clod}'
)
print(tabella.spinta.anova, caption.placement = "top")

@

La t-table \dubbio{Gigi dice che non si chiama t-table} (tabella
\ref{tab:sommario piccoli aggregati}) mostra come i terreni a
conduzione Biologica abbiano una densit\`a apparente minore rispetto a
quelli a conduzione Convenzionale; il terreno in cui \`e stata effettuata
l'aratura, risulta pi\`u denso rispetto ai terreni rippati e
frangizollati.



<<Summary_Petrolio, echo=FALSE, eval=TRUE, results=tex>>=

summary_spinta <- coef(summary_spinta)
rownames(summary_spinta) <-
c("CO Arato","Scostamento OO",
"Scostamento Frangizollato","Scostamento Rippato")

tabella.summary.spinta <- xtable(summary_spinta,
label = 'tab:sommario piccoli aggregati', align = 'lrrrr',
caption = 'sommario del modello adattato per i valori misurati con il metodo \\emph{Clod}'
)
print(tabella.summary.spinta, caption.placement = "top")
vec.paletti <- c(250, 20)
#vec.paletti <- c(180, 50)
#https://books.google.it/books?hl=it&lr=&id=gDnLAwAAQBAJ&oi=fnd&pg=PA15&dq=the+soil+habitat+voroney+heck&ots=rfoIOSpZhk&sig=4KK3HFUIYP2oAsd8FZIhEpv_iNg#v=onepage&q=the%20soil%20habitat%20voroney%20heck&f=false
@

<<label = qqplotPetrolio, fig.width=0.8, fig.height=0.8, echo=FALSE, eval = TRUE, fig=TRUE, include = FALSE>>=
par(mfrow = c(2,2))
plot(lm.spinta)
@ 


\section{Dinamica della distribuzione della dimensione degli aggregati}

<<Import_aggregati, echo = FALSE, eval = TRUE>>=
df.data <-
read.table(file.path(DirElab, "Stabilita_wide.csv"),
sep = ";", dec = ".", header=TRUE
)

df.data$TIME <- df.data$TIME-1 ## corregge i tempi che partono con 1
df.data$TIME2 <- df.data$TIME
UltraVeri <- which(df.data$Ultrasonic.level)
df.data$TIME2[UltraVeri] <- df.data$TIME2[UltraVeri]+12
##df.data[1:30, c("TIME", "TIME2", "Ultrasonic.level","Sample.Name")]
anomali32 <-
with(df.data,
which(Sample.Name == "32" & Ultrasonic.level & HUMIDITY == "dry"))
##df.data$TIME2[anomali32] <- 12:20

df.boyocous <-
read.table(file.path(DirData, "outputUSDA3.csv"),
sep = ";", dec = ",", header=TRUE
)

diametri <-
as.numeric(
substr(names(df.data)[19:119], 2,
nchar(names(df.data)[19:119]))
)


lis.paletti <-
list(uno=which(diametri > vec.paletti[1])+18,
due=which(diametri < vec.paletti[1] & diametri > vec.paletti[2] )+18,
tre=which(diametri < vec.paletti[2])+18
)

df.tessitura <-
data.frame(df.data[,c(1:13,18,120)],
MACRO = apply(df.data[,lis.paletti$uno], 1,
function(x) sum(x, na.rm=TRUE)),
MESO = apply(df.data[,lis.paletti$due], 1,
function(x) sum(x, na.rm=TRUE)),
MICRO = apply(df.data[,lis.paletti$tre], 1,
function(x) sum(x, na.rm=TRUE))
)
require(compositions)

###############################
## due umidit\`a con ultrasuoni
###############################

getModelMatrix <- function(object,
newdata=NULL,
na.action=na.pass) {
  if( is.null(newdata) )
  return(model.matrix(object))
  Terms <- delete.response(terms(object))
  mf <- model.frame(Terms,newdata,na.action=na.action,
  xlev = object$xlevels)
  if (!is.null(cl <- attr(Terms, "dataClasses")))
  .checkMFClasses(cl, mf)
  model.matrix(Terms, mf, contrasts.arg = object$contrasts)
}
lis.paletti <-
list(uno=which(diametri > vec.paletti[1])+18,
due=which(diametri < vec.paletti[1] & diametri > vec.paletti[2] )+18,
tre=which(diametri < vec.paletti[2])+18
)
df.tessitura <-
data.frame(df.data[,c(1:13,18,120)],
MACRO = apply(df.data[,lis.paletti$uno], 1,
function(x) sum(x, na.rm=TRUE)),
MESO = apply(df.data[,lis.paletti$due], 1,
function(x) sum(x, na.rm=TRUE)),
MICRO = apply(df.data[,lis.paletti$tre], 1,
function(x) sum(x, na.rm=TRUE))
)
questi <-
with(df.tessitura, which(HUMIDITY=="wet"))
df.plot <- df.tessitura[questi,]
Y.Msizer1 <-
acomp(df.plot[, 16:18])
lm.2 <-
with(df.plot, lm(ilr(Y.Msizer1) ~ COND+TIME2+I(TIME2^2)))

@





%% \migliora{ref aitchinson, analisi of compositional data, buccianti e

%% egozcue mettere nella discussione come mai si usano i composizionali

%% mettere nei matmet il modello usato mettere 10 alla meno 3 nella tabella 3.7

%% didascalia estesa in figura 3.4}


Per la costruzione dei modelli statistici \`e stato escluso il fattore
\emph{lavorazione} in quanto non significativi.

Nel modello statistico \`e presente la variabile continua \emph{tempo}
espressa al quadrato il quale, come \`e possibile vedere dalla tabella
ANOVA \ref{tab:anova_compWET}, \`e significativo.

La misura \`e stata effettuata sia su aggregati essiccati all'aria che
su aggregati inumiditi, per studiare il fenomeno dello
\emph{slaking}. Di conseguenza sono stati creati due modelli: uno per
i campioni inumiditi (\emph{WET}) e uno per i campioni secchi
(\emph{DRY}). Dai modelli \`e possibile vedere che pendenza
e curvatura siano comuni per entrambi i trattamenti.

I campioni essiccati generano, come atteso, frammenti di particelle
più grandi in seguito allo slaking.

L'analisi evidenzia che gli aggregati provenienti da appezzamenti
condotti convenzionalmente, successivamente all'immersione, si
disgregano generando frammenti pi\`u grandi di quanto non facciano gli
aggregati provenienti da appezzamenti a conduzione Biologica.  E
questo avviene sia con gli aggregati umidi che con quelli essiccati.

Questo comportamento mostrerebbe che le pratiche agricole utilizzate
nella conduzione di tipo \emph{Biologico} condurrebbero a formare aggregati
di meno stabili con cementi meno efficaci rispetto a quelli ottenuti
con la conduzione \emph{Convenzionale}.


<<label = plotacompWETDRY, fig.width=0.8, fig.height=0.8, echo=FALSE, eval = TRUE, fig=TRUE, include = FALSE>>=
modello <- lm.2
coefs <-  ilrInv(coef(modello), orig = Y.Msizer1)
alpha <- 0.05
plot(Y.Msizer1, cex=0.15, col=df.plot$COND, axes = TRUE, plotMissings = FALSE)
## macro meso micro
## plot(acomp(c(2,2,2)), pch = 20, cex = 2, add = TRUE, col = 1)
## plot(acomp(c(80,5,15)), pch = 20, cex = 2, add = TRUE, col = 2)
## plot(acomp(c(75, 5,20)), pch = 20, cex = 2, add = TRUE, col = 3)

## plot(acomp(c(5, 75,20)), pch = 20, cex = 2, add = TRUE, col = 3)

## plot(acomp(c(5, 55 ,40)), pch = 20, cex = 2, add = TRUE, col = 3)
on.ultra.off <- c(0, 11, 23)
CO <- round(matrix(coefs[1,] +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
ncol = 3, byrow = FALSE), 3)
OO <- round(matrix(acomp(coefs[1,]) +
acomp(coefs[2,]) +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
ncol = 3, byrow = FALSE), 3)
dati.iufd <- rbind(CO*100, OO*100)
#i = inizio, u = accension ultrasuoni, f = fine d = dry/w = wet
Conduzione <-
c("Convenzionale"," ", " ",
"Biologico "," "," ")
Fase <- rep(c("misura","inizio sonicatura", "fine misura"),2)
colnames(dati.iufd) <- c("Macro (%)", "Meso (%)", "Micro (%)")
df.iufd <- cbind(Conduzione, Fase, dati.iufd)
df.iufd <- rbind(df.iufd[1:3,], "", df.iufd[4:6,])



## banda.predizione <- FALSE
## for(i in 1:2){
  ##     for(k in 0:23){
    ##         newdata <-
    ##             list(COND = levels(df.plot$COND)[i],
    ##                  TIME2 = k)
    ##         X <- getModelMatrix(modello,newdata)
    ##         prediction <- ilrInv(predict(modello,newdata=newdata),orig=Y)
    ##         varEpsilon = var(modello)
    ##         XX <- kronecker(diag(ncol(predict(modello))),X)
    ##         estVar <- XX %*% vcov(modello) %*% t(XX)
    ##         predVar <- estVar+varEpsilon
    ##         plot(prediction,  add=TRUE, col= i, type= "b")
    ##         ## ellipses(prediction,ilrvar2clr(estVar),
    ##         ##          r=ConfRadius(modello,1-alpha), col=i)
    ##         if(banda.predizione)
    ##             ellipses(prediction,ilrvar2clr(predVar),
    ##                      r=ConfRadius(modello,1-alpha), col=i)
    ##     }
  ## }

plot(acomp(coefs[1,]) +
acomp(coefs[3,])*0:23 +
acomp(coefs[4,])*(0:23)^2,
col=1,  type="l", add=TRUE)## sequenza temporale CO
plot(acomp(coefs[1,]) + acomp(coefs[2,]) +
acomp(coefs[3,])*0:23+
acomp(coefs[4,])*(0:23)^2,
col=2, add=TRUE, type="l")## sequenza temporale OO
plot(acomp(coefs[1,]) +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
col=1, add=TRUE, pch=c("c", "D","C"))## start stop CO
plot(acomp(coefs[1,]) + acomp(coefs[2,]) +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
col=2, add=TRUE, pch= c("o","D","O"))## start stop OO

questi <-
with(df.tessitura, which(HUMIDITY=="dry"))
df.plot <- df.tessitura[questi,]
Y.Msizer <- acomp(df.plot[, 16:18])
lm.2.2 <-   with(df.plot,lm(ilr(Y.Msizer) ~ COND+TIME2+I(TIME2^2)))
modelloMsizer <- lm.2.2
coefs <-  ilrInv(coef(modelloMsizer), orig=Y.Msizer)
##############################################################
CO <- round(matrix(coefs[1,] +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
ncol = 3, byrow = FALSE), 3)
OO <- round(matrix(acomp(coefs[1,]) +
acomp(coefs[2,]) +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
ncol = 3, byrow = FALSE), 3)
dati.iufw <- rbind(CO*100, OO*100)
#i = inizio, u = accension ultrasuoni, f = fine d = dry/w = wet
rm(CO);rm(OO)
Conduzione <-
c("Convenzionale"," ", " ",
"Biologico "," "," ")
Fase <- rep(c("inizio misura","inizio sonicatura", "fine misura"),2)
colnames(dati.iufw) <- c("Macro (%)", "Meso (%)", "Micro (%)")
df.iufw <- cbind(Conduzione, Fase, dati.iufw)
df.iufw <- rbind(df.iufw[1:3,], "", df.iufw[4:6,])

plot(Y.Msizer, cex=0.25, col= as.numeric(df.plot$COND)+2, add=TRUE)
plot(acomp(coefs[1,]) +
acomp(coefs[3,])*0:23 +
acomp(coefs[4,])*(0:23)^2,
col=3,  type="l", add=TRUE)## sequenza temporale CO
plot(acomp(coefs[1,]) + acomp(coefs[2,]) +
acomp(coefs[3,])*0:23+
acomp(coefs[4,])*(0:23)^2,
col=4, add=TRUE, type="l")## sequenza temporale OO
plot(acomp(coefs[1,]) +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
col=3, add=TRUE, pch=c("c", "W","C"))## start stop CO
plot(acomp(coefs[1,]) + acomp(coefs[2,]) +
acomp(coefs[3,])*on.ultra.off +
acomp(coefs[4,])*on.ultra.off^2,
col=4, add=TRUE, pch= c("o","W","O"))## start stop OO
## for(i in 1:2){
  ##     for(k in 0:23){
    ##         newdata <-
    ##             list(COND = levels(df.plot$COND)[i],
    ##                  TIME2 = k)
    ##         X <- getModelMatrix(modello,newdata)
    ##         prediction <- ilrInv(predict(modello,newdata=newdata),orig=Y)
    ##         varEpsilon = var(modello)
    ##         XX <- kronecker(diag(ncol(predict(modello))),X)
    ##         estVar <- XX %*% vcov(modello) %*% t(XX)
    ##         predVar <- estVar+varEpsilon
    ##         plot(prediction,  add=TRUE, col= i, type= "b")
    ##         ## ellipses(prediction,ilrvar2clr(estVar),
    ##         ##          r=ConfRadius(modello,1-alpha), col=i)
    ##         if(banda.predizione)
    ##             ellipses(prediction,ilrvar2clr(predVar),
    ##                      r=ConfRadius(modello,1-alpha), col=i)
    ##     }
  ## }
legend("topleft",
c("Dry.CO", "Dry.OO", "CO.Wet", "OO.Wet"),
fill=1:4)
@


<<IUFW, echo=FALSE, eval=TRUE, results=tex>>=
xt.IUFW <- xtable(df.iufw,
label = 'tab:iufw', digits = 1,
caption = 'Distribuzione dei frammenti di particelle degli aggregati inumiditi in seguito a:
i) inizio misura (immersione):
ii) inizio sonicatura
iii) fine ciclo '
)
print(xt.IUFW,include.rownames=FALSE,caption.placement = "top")
@


<<IUFD, echo=FALSE, eval=TRUE, results=tex>>=
xt.IUFD <- xtable(df.iufd,
label = 'tab:iufd', digits = 1,
caption = 'Distribuzione dei frammenti di particelle degli aggregati essiccati in seguito a:
i) inizio misura (immersione):
ii) inizio sonicatura
iii) fine ciclo '
)
print(xt.IUFD, include.rownames=FALSE,caption.placement = "top")
@

<<anova_acompWET, echo=FALSE, eval=TRUE, results=tex>>=
anova.comp.wet <- anova(lm.2)
anova.comp.wet[1:4,6] <- "<10^-3"

rownames(anova.comp.wet) <- c("Intercetta","Conduzione", "Tempo", "Tempo^2","Residui")
anova_tabella <- xtable(anova.comp.wet,
label = 'tab:anova_compWET', align = 'lrrrrrr',
caption = 'ANOVA stabilit\\`a aggregati per i dati WET '
)
print(anova_tabella, caption.placement = "top")#, math.style.exponents = TRUE)
@



<<anova_acompDRY, echo=FALSE, eval=TRUE, results=tex>>=
anova.comp.dry <- anova(lm.2.2)
rownames(anova.comp.dry) <- c("Intercetta","Conduzione","Tempo", "Tempo^2","Residui")
anova.comp.dry[1:4,6] <- "<10^-3"
anova_tabella_dry<- xtable(anova.comp.dry,
label = 'tab:anova_compWET', align = 'lrrrrrr',
caption = 'ANOVA stabilit\\`a aggregati per i dati DRY '
)
print(anova_tabella_dry, caption.placement = "top")#, math.style.exponents = TRUE)
@




\begin{figure}[ht]
  \centering
<<label=figboh3,fig=TRUE,echo=FALSE, width=5.4, height=5.4>>=
<<plotacompWETDRY>>
@

  \caption[Evoluzione della distribuzione granulometrica delle
  particelle in seguito alla distruzione degli aggregati]{Evoluzione
    della distribuzione granulometrica delle particelle liberatisi in
    seguito a: \newline i) inizio misura (immersione, punti indicati
    dalle lettere minuscole \emph{c} e \emph{o}) \newline ii) accensione
    sonicatore (lettere \emph{W} e \emph{D}) \newline iii) fine ciclo.
    \newline Gli apici del triangolo rappresentano particelle maggiori
    di \Sexpr{vec.paletti[1]} (MACRO), comprese tra
    \Sexpr{vec.paletti[1]} e \Sexpr{vec.paletti[2]} (MESO) e inferiori a
    \SI{\Sexpr{vec.paletti[2]}}{\micro\metre} (MICRO)}
\end{figure}
\FloatBarrier


<<label = qqplotAcomp, fig.width=0.8, fig.height=0.8, echo=FALSE, eval = TRUE, fig=TRUE, include = FALSE>>=
qqnorm(ilrInv(resid(modelloMsizer), orig=Y.Msizer))
## il codice rimane qui, ma la figura è migrata alle appendici
@




\section{Distribuzione dimensionale dei pori}

<<Import_porosimetria, echo = FALSE, eval = TRUE>>=
#PoroElabora <- FALSE
# ## Si importano i soli file "CSV" MAIUSCOLI, che derivano dalla manipolazione dei dati grezzi della porosimetria
vec.paletti.poro <- c(0.05, 0.1) 
## if(PoroElabora){
  ##    source(file.path(DirCod, "ElaboraPorosimetriaConPaletti.R"))
  ##     }else{
  ##         NULL}

Export.Dir <-
file.path(DirMain, "dati_elaborati/porosimetria")
nomi.file.elab <- 
list.files(Export.Dir, pattern = ".CSV")

df.data <- data.frame()

for(i in 1:length(nomi.file.elab)){
  file.in.elaborazione <-
  nomi.file.elab[i]
  path.completo <-
  file.path(Export.Dir,file.in.elaborazione)
  df.this <-
  read.table(file=path.completo,
  sep=";", dec=",", header=TRUE,
  fileEncoding =  "UTF-16LE")[-4,]
  df.this$MAN <- substr(file.in.elaborazione, 3,3)
  df.this$FIELD <-  substr(file.in.elaborazione, 4,5 )
  df.this$TIL <-  substr(file.in.elaborazione, 6,6)
  df.this$ROW <-  substr(file.in.elaborazione, 7,7)
  df.this$REP <-  substr(file.in.elaborazione, 8,8)
  df.this$REPPORO <-  substr(file.in.elaborazione, 10,10)
  df.data <- rbind.data.frame(df.data, df.this)
}

df.data <- 
df.data[c(2,3,13:18)]

df.data <-
cbind.data.frame(df.data[c(T,F,F),-(1:2)],
matrix(df.data[,1], ncol=3, byrow=TRUE)
)        

names(df.data)[7:9] <-
c("micropori", "mesopori", "macropori")
require(compositions)
row.names(df.data) <- 1:dim(df.data)[1]
PESI <- read.table(file.path(DirElab, "pesoaggre.csv"), sep = ";")$x

df.data <- data.frame(
df.data[,1:6],
MICRO = (df.data[,7]-df.data[,8])/PESI, 
MESO = (df.data[,8]-df.data[,9])/PESI, 
MACRO = df.data[,9]/PESI
#    TOT = df.data[,7]/PESI
)

## lm.micropori <- 
##     with(df.data, lm(MICRO ~ MAN)) #+ TIL))
## anova(lm.micropori)
## summary(lm.micropori)
## lm.macropori <- 
##     with(df.data, lm(MACRO ~ MAN)) #+ TIL))
## anova(lm.macropori)
## summary(lm.macropori)
## lm.totale <- 
##     with(df.data, lm(TOT ~ MAN))#+TIL))
## anova(lm.totale)
## summary(lm.totale)


## par(mfrow = c(2,2))
## qqnorm(resid(lm.macropori))

## lm.ratio <-
##     lm(MACRO/MICRO ~ MAN*TIL, data = df.data)
## anova(lm.ratio)


df.porosimetria <-
df.data[-c(3,6,11,10),]

Y <- acomp(df.porosimetria[, 7:9])
modelloPoro <-
with(df.porosimetria, lm(ilr(Y) ~ MAN+TIL))
coefs.Poro <-  ilrInv(coef(modelloPoro), orig=Y)
alpha <- 0.05
##df.data$TOT <- rowSums(df.data[,7:8])
##df.data$P.INDEX <- df.data$TOT/df.data$PESI
## lm.totale <- 
##     lm(df.data$P.INDEX ~ df.data$MAN+df.data$TIL)
## lm.totale2 <- 
##     lm(df.data$P.INDEX ~ df.data$MAN*df.data$TIL)
## anova(lm.totale, lm.totale2)
##anova.PorTot <- 
##    anova(lm.totale)
@


I dati ottenuti sono stati analizzati mediante tecniche di analisi
composizionale. In Fig. \ref{fig:Poros_triangolo} e in tabella
\ref{tab:poros_anova} sono visibili i valori medi della composizione
per ogni combinazione di trattamenti.

<<summary_pori, eval = TRUE, echo = FALSE, results = tex>>=
sommario <- 
aggregate(Y, by = list(Conduzione = df.porosimetria$MAN, 
Lavorazione = df.porosimetria$TIL), 
function(x) round(mean(x),2)
)
attach(sommario)
sommario <- sommario[order(Conduzione, Lavorazione),]
detach(sommario)
sommario$Conduzione <- c("Convenzionale","","", "Biologico", "", "")
sommario$Lavorazione <- c("Arato", "Rippato", "Frangizollato", "Arato", "Rippato", "Frangizollato")

tabella_sommario <- 
xtable(sommario,
caption = "Sommario della distribuzione dei pori nelle tre classi dimensionali dei dati ottenuti dalla analisi con porosimetria a mercurio", label = 'tab:Poro_medie', align = "lllccc")
print(tabella_sommario, include.rownames=FALSE,
caption.placement = "top",
table.placement= "hb")
anova.poros <- round(anova(modelloPoro), 3)
rownames(anova.poros) <- c("Intercetta","Conduzione", "Lavorazione","Residui")
anova.poros[1,6] <- "<10^-3"
anova_tabella <- xtable(anova.poros,
label = 'tab:poros_anova', align = 'lrrrrrr',
caption = 'ANOVA del modello composizionale dei dati ottenuti dalle analisi con porosimetria a mercurio '
)
print(anova_tabella, caption.placement = "top")#, math.style.exponents = TRUE)
@ 

\`E possibile evincere come i dati non permettano di evidenziare delle
differenze. I punti all'interno del diagramma ternario si trovano
tutti ravvicinati all'apice dei macropori (maggiori di
\Sexpr{vec.paletti.poro[2]} \SI{}{\micro\metre} (macropori)).

<<label = plotacompPore, echo=FALSE, eval = TRUE, fig=TRUE, include = FALSE>>=
plot(Y, cex=0.15, col=as.numeric(df.porosimetria$MAN), axes = TRUE)
intercetta <-
ilrInv(coef(modelloPoro)[1,], orig=Y)
bi <-
ilrInv(rbind(0, coef(modelloPoro)[-1,]), orig=Y)
medie <- intercetta+acomp(bi)
plot(medie, col=as.factor(df.porosimetria$TIL), add = TRUE)

@

% \noindent%
% \begin{minipage}{\linewidth}% to keep image and caption on one page
%   \makebox[\linewidth]{%        to center the image
\begin{figure}[ht]
  \centering
<<label = figurina, fig=TRUE, echo=FALSE, width=4.5, height=4.5>>=
<<plotacompPore>>
@
  \caption[didascalia corta]{Diagramma ternario della distribuzione dei
    pori. Gli apici del triangolo rappresentano le classi dimensionali
    in cui i pori sono divisi in: inferiori di
    \Sexpr{vec.paletti.poro[1]} (micropori), comprese tra
    \Sexpr{vec.paletti.poro[1]} e \Sexpr{vec.paletti.poro[2]} (mesopori)
    e superiori di \Sexpr{vec.paletti.poro[2]} \SI{}{\micro\metre}
    (macropori)}
  \label{fig:Poros_triangolo}
\end{figure}
% \end{minipage}
\FloatBarrier

La tabella \ref{tab:poros_anova}, mostra che all'interno dei
trattamenti non sono presenti differenze statisticamente
significative. Di conseguenza, dato il basso numero di campioni, non
\`e possibile evidenziare una significativit\`a dei trattamenti.

Considerato che le tecniche di statistica composizionale non
considerano la somma totale delle composizioni ma i loro rapporti
(appendice \ref{sec:composizionale}), \`e stata tentata una analisi
statistica univariata prendendo come variabile dipendente il valore
della porosit\`a totale del campione, normalizzato al suo peso.


<<pori_totali, eval = TRUE, echo = FALSE, results = tex>>=
lm.totale <- 
lm(MICRO+MACRO+MESO ~ MAN, data = df.data)
anova.totale <- 
anova(lm.totale)
rownames(anova.totale) <- c("Conduzione", "Residui")
anova_tabellaTot <- xtable(anova.totale,
label = 'tab:tot_anova', align = 'lrrrrr',
caption = 'ANOVA del modello adattato alla porosit\\`a totale'
)
print(anova_tabellaTot, caption.placement = "top")#, math.style.exponents = TRUE)
@ 


La tabella Anova \ref{tab:tot_anova} ci permette di affermare che il
numero di campioni non \`e sufficiente per determinare la
significativit\`a dei trattamenti, tuttavia come si pu\`o vedere dalla
tabella \ref{tab:tot_sommario}, i dati tenderebbero a confermare il
risultato dell'analisi della densit\`a apparente misurata con il
metodo \emph{Clod} dal quale risultava una maggior porosit\`a nei
campioni di suolo provenienti da appezzamenti condotti a \emph{Biologico}.


<<sommario_totali, eval = TRUE, echo = FALSE, results = tex>>=
sommario.totale <- 
    round(coef(summary(lm.totale)),3)
rownames(sommario.totale) <- 
    c("Convenzionale", "Biologico")
sommario.totale[1,4] <- "<10^-3" 
sommario_tabellaTot <- xtable(sommario.totale,
label = 'tab:tot_sommario', align = 'lrrrr',
caption = 'Sommario del modello adattato alla porosit\\`a totale'
)
print(sommario_tabellaTot, caption.placement = "top")#, math.style.exponents = TRUE)
@ 



<<hist_pori, eval = FALSE, echo = FALSE, results = tex>>=
nomi.file.elab <- list.files(Export.Dir, pattern = ".csv")
df.rawdata <- data.frame()
for(i in 1:length(nomi.file.elab)){
  file.in.elaborazione <-
  nomi.file.elab[i]
  path.completo <-
  file.path(Export.Dir,file.in.elaborazione)
  df.this <-
  read.table(file=path.completo,
  sep=";", dec=",", header=TRUE,
  fileEncoding =  "UTF-16LE")[,c(2:5)]
  df.this$MAN <- substr(file.in.elaborazione, 3,3)
  df.this$FIELD <-  substr(file.in.elaborazione, 4,5 )
  df.this$TIL <-  substr(file.in.elaborazione, 6,6)
  df.this$ROW <-  substr(file.in.elaborazione, 7,7)
  df.this$REP <-  substr(file.in.elaborazione, 8,8)
  df.this$REPPORO <-  substr(file.in.elaborazione, 10,10)
  df.this$SUBJECT <-  substr(file.in.elaborazione, 3,10)
  df.rawdata <- rbind.data.frame(df.rawdata, df.this)
}
names(df.rawdata)[1] <- "Volume"
require(lattice)
hist.esteso <- histogram(~Volume|SUBJECT, data=df.rawdata)
# xyplot(Volume.NA ~ log(Radius.NA, base=10) |MAN+TIL, data=df.rawdata)
hist.media <- histogram( ~ Volume |MAN+TIL, data=df.rawdata)
@

% \begin{figure}[ht]
%   \centering
%   <<label = istrogrammiPoro1, fig=TRUE, echo=FALSE, width=5.4, height=5.4>>=
%   print(hist.esteso)

%   @
%   \caption[didascalia corta]{Distribuzione dei pori in ogni campione misurato
% }
%   \label{fig:Poros_hist}
% \end{figure}

% \begin{figure}[ht]
%   \centering
%   <<label = istogrammiPoro2, fig=TRUE, echo=FALSE, width=5.4, height=5.4>>=
%   print(hist.media)
%   @

%   \caption[didascalia corta]{Distribuzione dei pori: media dei trattamenti}
%   \label{fig:Poros_hist}
% \end{figure}

%% Essendo la statistica composizionale un tipo di analisi che li

%% <<anova_tot, eval = TRUE, echo = FALSE, results = tex>>=
%% tabella_PorTot <- 
%% xtable(anova.PorTot,
%% caption = "Tabella anova della porosit\\`a totale", label = 'tab:Poro_Tot', align = "llcccc")
%% print(tabella_PorTot, include.rownames=FALSE,
%% caption.placement = "top",
%% table.placement= "hb")
%% @ 










\chapter{Discussione}

L'ipotesi che ci ha portato ad effettuare questa misurazione \`e data
dal fatto che la conduzione Biologica, non utilizzando concimi e
pesticidi di sintesi, avrebbe un minor impatto sulla microflora e
microfauna tellurica, e di conseguenza ci aspetteremmo una migliore
struttura favorita dall'attivit\`a biologica.  

Dai risultati della densit\`a apparente \`e emerso che:
\begin{itemize}
\item la densit\`a apparente misurata tramite metodo \emph{Core},
  non evidenzia differenze statisticamente significative tra i trattamenti;
\item la densit\`a apparente misurata tramite metodo \emph{Clod}
  mostra differenze statisticamente significative tra i trattamenti.
\end{itemize}

Come si pu\`o notare confrontando la tabella \ref{tab:summaryCore} con
la tabella \ref{tab:summaryClod}, il metodo \emph{Clod} fornisce
dei  valori di  densit\`a apparente  pi\`u elevati  rispetto a  quelli
misurati utilizzando il metodo \emph{Core}, questo \`e dovuto al fatto
che    nella    misura    non    sono    considerate    le    fratture
\citep{tisdall1951comparison}.

I dati si allineano con ci\`o che hanno rilevato altri autori
(\citet{williams2017organic}, \citet{green2005soil},
\citet{ikemura2008some}, \citet{vian2009effects}), ovvero una
densit\`a apparente con valori mediamente pi\`u bassi nei terreni
condotti ad agricoltura Biologica rispetto ai terreni condotti ad
agricoltura Convenzionale e nei terreni lavorati superficialmente
rispetto a quelli lavorati pi\`u in profondit\`a.

La t-table in tabella \ref{tab:anova piccoli aggregati} mostra che,
nonostante la rilevata significativit\`a statistica, le differenze di
densit\`a sono dell'ordine della seconda cifra decimale. Questo ci
permette di affermare: in primo luogo che il numero di campioni \`e
idoneo agli obiettivi dello studio, in secondo luogo che i trattamenti
non risultano significativi dal punto di vista tecnologico, ovvero non
hanno una rilevanza pratica effettiva. 

Dall'analisi della stabilit\`a degli aggregati \`e emersa una maggiore
stabilit\`a degli aggregati Convenzionali rispetto agli aggregati
Biologici. Mentre tra le lavorazioni non risultano differenze
statisticamente significative.

Alla fine del trattamento disgregativo con ultrasuoni, tutti gli
aggregati convergono in un punto che coincide con i dati disponibili
sulla distribuzione tessiturale del sito di prelievo dei campioni.

I risultati vanno in controtendenza a ci\`o che hanno rilevato altri
autori come \citet{siegrist1998does}, \citet{williams2017organic} e
\citet{green2005soil}.

Questo pu\`o essere dato dal fatto che nell'appezzamento coltivato a
Biologico non sono state effettuate concimazioni, quindi la sostanza
organica non \`e stata reintegrata in nessun modo.

Nell'appezzamento Convenzionale, al contrario, sono state effettuate
concimazioni con fertilizzanti di sintesi. Questo ha portato ad un
aumento delle radici superficiali con conseguente incremento della
biomassa nei primi \SI{20}{\centi\meter} di suolo.

Secondo \citet{mizuta2015soil}, la stabilit\`a degli aggregati dipende
esclusivamente dal contenuto di sostanza organica e non dal tipo di
molecole organiche coinvolte, tuttavia secondo \citet{d2017physical}
la stabilit\`a degli aggregati \`e fortemente influenzata dalla
sostanza organica protetta. È quindi necessario ripetere la misura di
stabilit\`a in seguito alla rimozione della sostanza organica
superficiale, per comprendere se la conduzione influenzi diversi tipi
di sostanza organica.

Per quanto riguarda la distribuzione dei pori non sono state
riscontrate differenze significative tra i trattamenti.

Tuttavia i dati mostrano come i campioni biologici tendano ad avere
una maggior porosit\`a rispetto ai campioni convenzionali, in linea
con quanto riscontrato dall'analisi \emph{Clod} e con quanto hanno
trovato altri autori (\citep{ikemura2008some} e \citep{mendoza2011assessment}).

\chapter{Conclusioni}

Dai risultati \`e emerso che gli indicatori dello stato fisico del
suolo non sono in grado di evidenziare differenze significative 
\begin{itemize}
\item Densità
  \begin{itemize}
  \item Nessuna differenza col metodo Core. Se si osserva è solo
    perchè si usano molti campioni per OO nel 2015. La differenza è
    sulla seconda decimale, quindi tecnicamente superflua
  \item Il metodo \emph{Clod} mostra delle differenze per due
    combinazioni di trattamenti
  \end{itemize}
\item Stabilità aggregati
\item Porosimetria
  
\end{itemize}



\appendix
  \chapter{Misurazione delle distribuzioni
    granulometriche ottenuta mediante Mastersizer 2000}
  Lo strumento Mastersizer 2000 si basa sul fenomeno della diffusione
  ottica (scattering), ovvero \emph{un'ampia classe di fenomeni di
    interazione radiazione-materia in cui onde o particelle vengono
    deflesse ovvero cambiano traiettoria, a seconda della collisione
    con altre particelle o onde (dal punto di vista quantistico) in
    maniera disordinata e in buona maniera casuale}
  \citep{scattering}.

  Le equazioni che descrivono lo scattering sono molto complesse; nel
  caso in cui le particelle abbiano dimensione maggiore della lunghezza
  d'onda della radiazione luminosa incidente, esiste (assumendo la
  perfetta sfericit\`a delle particelle) una soluzione matematicamente
  rigorosa, detta \emph{Soluzione di Mie}.

  \begin{figure}[ht]
    \centering
    \includegraphics[width=0.7\textwidth]{../foto/Mie_scattering.jpeg}
    \caption[Scattering di Mie]{In figura \`e rappresentato il fenomeno
      dello scattering di Mie, presa da
      \url{http://www.smart-piv.com/en/techniques/mie-rayleigh-raman/index.php}}%{questo
                                %sito}}
    \label{fig:Mie}
  \end{figure}
\FloatBarrier

  Se la dimensione delle particelle in dettagli riguardanti la loro
  struttura sono noti, il modo in cui diffondono la luce pu\`o essere
  previsto accuratamente. Ogni dimensione della particella avr\`a il suo
  caratteristico pattern di diffusione che sar\`a diverso da quello di
  qualsiasi altra particella a diversa dimensione.

  Facendo il ragionamento inverso \`e quindi possibile calcolare la
  dimensione delle particelle in base al pattern di diffusione.

  \begin{figure}[ht]
    \centering
    \includegraphics[width=0.7\textwidth]{../foto/laser_diffraction.jpeg}
    \caption[Schema di funzionamento del Mastersizer
    2000]{Rappresentazione del funzionamento del Mastersizer 2000 presa
      da:
      %\href
      \url{https://plus.google.com/communities/110676150876604729660/stream/ffa7f40a-1c65-4268-9121-bb88d63f0c41}}%{questo
                                %sito}}
    \label{fig:MastersizerInt}
  \end{figure}
  \FloatBarrier

  Per calcolare la classe dimensionale, il software utilizza la
  legge di \emph{Lambert-Beer}:

  \begin{equation}
    \label{eq:BeerLambert}
    \frac{I}{I_0}=e^{-\alpha b}
  \end{equation}

  dove:\\
  \begin{tabular}{rp{12cm}}
    $I$            & è l'intensit\`a della luce a una distanza $b$ dal campo
                     delle particelle di assorbanza $\alpha$\\
    $I_0$          & è l'intensit\`a della radiazione luminosa all'ingresso
                     del campo delle particelle 
  \end{tabular}
  Il rapporto a sinistra dell'equazione ($\frac{I}{I_0}$) rappresenta
  la trasmittanza T del raggio (misurata direttamente dallo
  strumento), ovvero, $I_0$ \`e l'intensit\`a del laser quando nessun
  campione \`e presente e $I$ \`e l'intensit\`a con il campione
  presente.


  Ri-arrangiando l'equazione \ref{eq:BeerLambert}:

  \begin{equation}
    \alpha=\frac{-1}{b}ln \langle T \rangle
  \end{equation}

  Il termine $\alpha$ contiene informazioni concernenti la
  concentrazione volumetrica riguardo alle particelle di una
  determinata classe dimensionale.

  Secondo la teoria dello scattering, la luce attenuata da una particella
  $i$ pu\`o essere descritta da:

  \begin{equation}
    a_i=Q_i\pi r_i^2n_i
    \label{eq:Msizer_Luce_Attenuata}
  \end{equation}

  dove:\\
  \begin{tabular}{rp{12cm}}
    $a_i$       &  \`e la dimensione della particella i\\
    $Q_i$       &  \`e l'efficienza dell'estinzione luminosa calcolata dalla
                  teoria Mie per una particella di raggio $r_i$\\
    $\pi r_i^2$ &  \`e l'area della sezione della particella\\
    $n_i$       &  \`e il numero di particelle di raggio $r_i$
                      
  \end{tabular}

  Considerando la formula per il calcolo del volume delle particelle
  sferiche($V_i=\frac{4}{3}\pi r_i^3n_i$), l'equazione
  \ref{eq:Msizer_Luce_Attenuata}, per un insieme di
  particelle, diventa:

  \begin{equation}
    \alpha_i=\frac{3}{4} \sum \frac{Q_iV_i}{r_i}
  \end{equation}

  La dimensione delle particelle \`e espressa in base al diametro $d$ e
  il volume pu\`o essere separato in una distribuzione relativa dei
  volumi $v$ e in una concentrazione totale $C_v$ (volume totale delle
  particelle in una unit\`a di volume del disperdente). L'equazione
  quindi diventa:

  \begin{equation}
    \alpha_i=\frac{3}{2} \sum \frac{Q_iV_i}{d_i}
  \end{equation}

  Uguagliandola con la formula \ref{eq:BeerLambert}, si ottiene:
  \begin{equation}
    C_v=\frac{-2 Ln \langle T \rangle}{3b \sum \frac{Q_iv_i}{d_i}}
  \end{equation}

  Se $d$ \`e espresso in $\mu$m e b in mm, allora $v$ \`e la
  concentrazione relativa della distribuzione del volume (in cui $\sum
  v_i=1$) allora:

  \begin{equation}
    \label{eq:Msizer_ppm}
    C_v(ppm)=\frac{-2000 Ln \langle T \rangle}{3b \sum \frac{Q_iv_i}{d_i}}
  \end{equation}

  Nell'equazione \ref{eq:Msizer_ppm}:

  \begin{tabular}{rp{12cm}}
    $\langle T \rangle$ &  Trasmittanza, \`e un valore compreso tra 0 e 1 ed \`e
                          misurato direttamente dallo strumento\\
    $v_i$ & \`e la distribuzione di particelle, ovvero il volume relativo
            nella classe dimensionale $i$ con diametro medio $d_i$\\
    $Q_i$, & il coefficiente di estinzione medio per la classe
             dimensionale $i$, \`e calcolato dalla teoria dello scattering, ed
             \`e una funzione delle propriet\`a ottiche delle particelle e del
             mezzo disperdente.
  \end{tabular}
  Questa equazione ci fornisce la concentrazione delle particelle
  della classe dimensionale $i$ in parti per milione (ppm). La
  percentuale di concentrazione del volume viene calcolata dividendo
  il valore finale per 10000.
  
  I precedenti calcoli partono dall'assunto che le particelle misurate
  siano sfere perfette. In pratica questo avviene raramente e questo
  causa problemi in termini di misura della dimensione delle
  particelle: se le particelle sono in una forma irregolare, quale
  delle tre dimensioni dello spazio (altezza, larghezza, profondit\`a)
  dovrei misurare?
  
  Lo scopo dello strumento \`e quello di fornire un singolo numero che
  descriva la dimensione delle particelle, per esempio:
  \begin{itemize}
    \item il diametro teorico di una sfera che abbia la stessa
      superficie della particella originale;
    \item la dimensione massima della particella misurata, impiegata
      come diametro di una sfera teorica;
    \item la dimensione minima della particella misurata,
      impiegata come diametro di una sfera teorica;
    \item il diametro teorico di una sfera che abbia lo stesso volume
      della particella originale;
  \end{itemize}
  
  Il Mastersizer utilizza quest'ultimo metodo. Ognuno di questi metodi
  \`e accettabile, ma ognuno fornisce una dimensione differente,
  \`e dunque possibile confrontare seriamente le misure che sono state
  effettuate utilizzando lo stesso metodo.
  
  
  
  
  \chapter{Princ\`ipi di unzionamento della porosimetria ad intrusione
    di mercurio}

  La distribuzione dei pori nei campioni di suolo \`e stata rilevata mediante due
  porosimetri ad intrusione di mercurio: il PASCAL 140
  \citep{Pascal_140} per la misura della microporosit\`a e il
  Porosimetro Carlo Erba 2000 series \citep{carli1989particle} per
  quella della macroporosit\`a.

  Entrambi gli strumenti sono formati da tre macroblocchi:
  \begin{enumerate}
  \item un dilatometro, in cui viene immesso il campione pesato;
  \item un sistema di pressurizzazione, che include una pompa peristaltica
    per l'aria, un moltiplicatore di pressione e una autoclave;
  \item un sistema di misura del volume e della pressione del
    mercurio che viene intruso nel campione.
  \end{enumerate}

  La determinazione della dimensione dei pori mediante la tecnica a
  penetrazione di mercurio \`e basata sul comportamento dei liquidi
  non bagnanti nei capillari. Un liquido non pu\`o spontaneamente
  entrare in un poro che ha un angolo di contatto superficie/liquido maggiore di
  \SI{90}{\degree} a causa della tensione superficiale, comunque
  questa resistenza pu\`o essere superata grazie a una pressione
  esterna.

  La pressione richiesta per vincere tale resistenza, \`e in funzione della dimensione dei pori, la
  relazione tra la dimensione dei pori e la pressione esercitata quando
  un poro viene considerato cilindrico \`e espresso dalla seguente
  relazione, detta equazione di Washburn:

  \begin{equation}
    pr=2\sigma cos \theta
    \label{eq:Washburn}
  \end{equation}

  \begin{tabular}{rp{12cm}}
    $p$ &  \`e la pressione assoluta applicata (\SI{}{\kilogram \per \centi \meter \squared})\\
    $r$      &  \`e il raggio dei pori (\SI{}{\nano\meter})\\
    $\sigma$ & \`e la tensione superficiale del mercurio (\SI{}{\meter \newton \per \meter \squared})\\
    $\theta$ & \`e l'angolo di contatto (\SI{}{\celsius})
  \end{tabular}

  Nonostante che quasi tutte le sostanze porose abbiano pori sferici e
  non cilindrici, questa equazione \`e generalmente usata per
  calcolare la distribuzione dei pori a partire da dati derivati da
  tecniche di analisi per porosimetria ad intrusione di mercurio.

  L'equazione di Washburn \`e derivata dalla seguente considerazione:
  \emph{in un capillare con una sezione circolare, la tensione
    superficiale del liquido \`e esercitata nell'area di contatto in cui
    la circonferenza del poro \`e superiore all'area di contatto.}

  La forza $2\pi r \sigma$, \`e perpendicolare al piano della superficie
  di contatto.

  La forza che tende a spingere il liquido all'esterno del capillare \`e:
  \begin{equation}
    2\pi r \sigma_i cos \theta
    \label{eq:forzaliqu}
  \end{equation}

  Contro questa forza, la pressione esterna che dovr\`a essere
  esercitata sull'area della superficie di contatto sar\`a uguale a:

  \begin{equation}
    \pi r^2 p
    \label{eq:forzacont}
  \end{equation}

  Quando l'equilibrio \`e raggiunto, queste due forze si equivalgono.
  L'equazione \ref{eq:Washburn} espressa in funzione della pressione sar\`a:

  \begin{equation}
    r=\frac{2\sigma cos \theta}{p}
    \label{eq:WashburnP}
  \end{equation}

  Sapendo le caratteristiche fisiche del mercurio (tensione superficiale
  di \SI{480}{\meter \newton \per \meter \squared} e angolo di contatto
  di \SI{143.1}{\degree}) e assumendo i pori come cilindrici, si ottiene
  la seguente relazione:
  \begin{equation}
    r=7500/P
    \label{eq:WashburnHg}
  \end{equation}

  dove:\\
  \begin{tabular}{rp{12cm}}
    $r$ &  \`e il raggio dei pori, espresso in \SI{}{\nano\meter}\\
    $p$ &  \`e la pressione assoluta applicata, espressa in
          \SI{}{\kilogram \per \centi \meter \squared}
  \end{tabular}

  Per i pori irregolari, il rapporto tra la sezione trasversale dei
  pori (relativa alla pressione esercitata) e alla circonferenza dei
  pori (relativa alla tensione superficiale) non \`e proporzionale al
  raggio e dipende dalla forma del poro e l'equazione
  \ref{eq:WashburnHg} dar\`a valori pi\`u bassi.

  Il volume di mercurio penetrato corrisponde al volume del poro del
  campione espresso in \SI{}{\mm \cubed}, ed \`e acquisito tramite un
  sensore elettrico capacitivo, in cui: un'armatura \`e rappresentata
  da un elettrodo tubulare esterno, fissato al dilatometro; l'altra
  \`e rappresentata dalla colonnina di mercurio interna al
  dilatometro. In Fig. \ref{fig:dilatometro} \`e rappresentato il
  dilatometro utilizzato.
  \begin{figure}
    \centering
    \includegraphics[width=0.6\textwidth]{../foto/dilatometro.jpeg}
    \caption[Schema di funzionamento del dilatometro]{Rappresentazione
    del dilatometro con sistema di misura capacitivo, immagine ripresa dal
    manuale utente dello strumento Pascal 140}
    \label{fig:dilatometro}
  \end{figure}
  
  Con gli incrementi di pressione e in presenza di penetrazione, la
  colonna di mercurio caler\`a, permettendo di misurare il valore
  della capacit\`a in funzione della penetrazione.
  
  Siccome l'abbassamento della colonna sar\`a influenzato anche dalla compressibilit\`a
  del mercurio (e non solo dalla sua penetrazione) \`e necessario
  effettuare una prova preliminare in bianco.


  \chapter{Dati composizionali: natura e metodi di analisi}
  \label{sec:composizionale}
  In questa tesi sono state utilizzate tecniche di analisi per dati
  composizionali  \citep{van2013analyzing}.
  
  Un dataset pu\`o essere definito composizionale se contiene porzioni
  di un totale. Ad esempio: la percentuale di lavoratori in differenti settori,
  le porzioni di elementi chimici in un minerale, la tessitura di un suolo,
  ecc.

  Le parti individuali del dataset composizionale sono chiamate
  \emph{componenti}. Ogni \emph{componente} ha una quota (in valori
  assoluti o relativi), rappresentata dalla sua frazione sul totale.

  I metodi classici di analisi utilizzati per i dati scalari non
  possono essere applicati per i dati composizionali che richiedono
  quindi i metodi statistici appropriati
  \citep{aitchison1986statistical}.

  La caratteristica fondamentale dei dati composizionali \`e che non
  siamo interessati alla somma totale delle composizioni, questo accade
  per diverse ragioni:
  \begin{itemize}
  \item quando i dati composizionali sono misurati, possiamo
    influenzare il totale;
  \item spesso il totale delle composizioni non \`e completo e non dà
    la somma del totale "reale";
  \item tipicamente, il totale non \`e comparabile tra le diverse
    unit\`a statistiche.
  \end{itemize}

  Una composizione \`e sempre formata da pi\`u subcomposizioni. E la
  stessa composizione di partenza \`e a sua volta una subcomposizione.

  Nonostante ci\`o, l'analisi dei dati composizionali \`e eseguibile
  anche su dataset a cui mancano delle componenti irrilevanti, questa
  \`e chiamata 'coerenza subcomposizionale'
  \citep{aitchison1986statistical}.
  
  La coerenza subcomposizionale si applica tutte le volte che \emph{si
    chiude} una composzizione. Ad esempio: gli elementi presenti
  nell'acqua sono molteplici ma hanno in genere concentrazioni ben
  diverse: possiamo infatti dividerli in macro e microelementi. La
  composizione totale dovrebbe comprenderli tutti, ma a seconda dello
  studio, la \emph{chiusura} delle percentuali viene fatta per i soli
  macro o per i soli micro; oppure nel caso di uno studio di chimica
  del suolo si pu\`o considerare le sole basi di scambio presenti,
  anche in questo caso si pu\`o considerare solamente il totale della
  subcomposizione.
  
  I dati composizionali vengono sempre trattati in una
  \emph{log-ratio-transformed scale}. Questo operazione porta a
  definire uno spazio vettoriale ristretto, contenuto nello spazio
  reale, denominato \emph{simplesso}.

  In questo spazio vettoriale le relazioni sono linearizzate e quindi
  \`e possibile utilizzare tutte le tecniche di statistica
  multivariata: regressione, anova, modelli lineari, ecc.


\chapter{Grafici dei residui dei modelli statistici utilizzati per l'analisi dei
    dati}
\label{sec:residui}
\begin{figure}[ht]
    \centering
<<label = figkek, fig = TRUE, echo = FALSE>>=
<<qqplotCampo>>
@ 

\caption[Plot Core]{Plot del modello densit\`a con metodo \emph{Core}.\newline In
  alto a destra si può vedere come la varianza sia costante lungo
  l'asse dei valori adattati dal modello lineare;\newline in alto a
  sinistra abbiamo il qqplot, il quale ci conferma che i residui
  assumono una distribuzione normale;\newline in basso a sinistra,
  viene ripetuta la verifica della varianza costante con i valori dei
  residui standardizzati, anche in questo caso la varianza \`e
  costante;\newline in basso a destra sono presenti rappresentati i
  punti di leverage (...)}
    \label{fig:qqplotCore}
\end{figure}
\FloatBarrier


\begin{figure}[ht]
  \centering
<<label = figlel, fig = TRUE, echo = FALSE>>=
<<qqplotPetrolio>>
@ 

\caption[Plot Clod]{Plot del modello densit\`a con metodo \emph{Clod}\newline In
  alto a destra si può vedere come la varianza sia costante lungo
  l'asse dei valori adattati dal modello lineare;\newline in alto a
  sinistra abbiamo il qqplot, il quale ci conferma che i residui
  assumono una distribuzione normale;\newline in basso a sinistra,
  viene ripetuta la verifica della varianza costante con i valori dei
  residui standardizzati, anche in questo caso la varianza \`e
  costante;\newline in basso a destra sono presenti rappresentati i
  punti di leverage (...)}
   \label{fig:qqplotClod}
\end{figure}
\FloatBarrier


\begin{figure}[ht]
  \centering
<<label=figboh4, fig=TRUE, echo=FALSE>>=
<<qqplotAcomp>>
@
  \caption[qqplot stabilit\`a]{Grafico quantile-quantile per i residui del modello statistico
    composizionale per la stabilità degli aggregati}
  \label{fig:qqplot_dinamica_aggregati}
\end{figure}
\FloatBarrier


  
<<label = qqplotpori, fig.width=0.5, fig.height=0.5, echo=FALSE, eval = TRUE, fig=TRUE, include = FALSE>>=
 qqnorm(ilrInv(resid(modelloPoro), orig=Y))
@ 

 \begin{figure}[ht]
  \centering
<<label = figurina2, fig = TRUE, echo=FALSE>>=
<<qqplotpori>>
@
  \caption[qqplot porosimetria]{Grafico quantile-quantile per i residui del modello
    composizionale per i dati di porosimetria}
  \label{fig:qqplot_porosimetria}
\end{figure}
\FloatBarrier

  %% <<label = qqplotPorTot, fig.width=0.5, fig.height=0.5, echo=FALSE, eval = TRUE, fig=TRUE, include = FALSE>>=
  %% qqnorm(resid(lm.totale), orig=Y)
  %% qqline(resid(lm.totale))
  %% @ 

  %% \begin{figure}[ht]
  %%   \centering
  %%   <<label = figurina3, fig = TRUE, echo=FALSE>>=
  %%   <<qqplotPorTot>>
  %%   @
  %%   \caption{Grafico quantile-quantile per i residui del modello
  %%   per i dati totali di porosimetria}
  %%   \label{fig:qqplot_PorTot}
  %% \end{figure}



\nonvisibile{Simo: pagina 143 Pantieri per sitografia}
\listoffigures % non funziona con xtable
\listoftables
% \section*{\refname}
\printbibliography[nottype=misc]
\printbibliography[heading=web,type=misc]
\end{document}
